//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCDIntegrations.MoEcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.informatica.com/dis/ws/", ConfigurationName="MoEcService.MOE_getTradeLicenseBasicByEIDPPPortType")]
    public interface MOE_getTradeLicenseBasicByEIDPPPortType {
        
        // CODEGEN: Generating message contract since the operation GetTradeLicenseBasicByEIDPP is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Output GetTradeLicenseBasicByEIDPP(MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Input request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Output> GetTradeLicenseBasicByEIDPPAsync(MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Input request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.informatica.com/dis/ws/")]
    public partial class GetTradeLicenseBasicByEIDPP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emiratesIDField;
        
        private string passportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmiratesID {
            get {
                return this.emiratesIDField;
            }
            set {
                this.emiratesIDField = value;
                this.RaisePropertyChanged("EmiratesID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Passport {
            get {
                return this.passportField;
            }
            set {
                this.passportField = value;
                this.RaisePropertyChanged("Passport");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.informatica.com/dis/ws/")]
    public partial class GetTradeLicenseBasicByEIDPPResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetTradeLicenseBasicByEIDPPResponseOwnerDetails[] ownerDetailsField;
        
        private GetTradeLicenseBasicByEIDPPResponseError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OwnerDetails", Order=0)]
        public GetTradeLicenseBasicByEIDPPResponseOwnerDetails[] OwnerDetails {
            get {
                return this.ownerDetailsField;
            }
            set {
                this.ownerDetailsField = value;
                this.RaisePropertyChanged("OwnerDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GetTradeLicenseBasicByEIDPPResponseError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.informatica.com/dis/ws/")]
    public partial class GetTradeLicenseBasicByEIDPPResponseOwnerDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ownerEmiratesIDField;
        
        private string ownerNameARField;
        
        private string ownerNameENField;
        
        private string ownerPassportField;
        
        private GetTradeLicenseBasicByEIDPPResponseOwnerDetailsBusinessLicenses[] businessLicensesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OwnerEmiratesID {
            get {
                return this.ownerEmiratesIDField;
            }
            set {
                this.ownerEmiratesIDField = value;
                this.RaisePropertyChanged("OwnerEmiratesID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OwnerNameAR {
            get {
                return this.ownerNameARField;
            }
            set {
                this.ownerNameARField = value;
                this.RaisePropertyChanged("OwnerNameAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OwnerNameEN {
            get {
                return this.ownerNameENField;
            }
            set {
                this.ownerNameENField = value;
                this.RaisePropertyChanged("OwnerNameEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OwnerPassport {
            get {
                return this.ownerPassportField;
            }
            set {
                this.ownerPassportField = value;
                this.RaisePropertyChanged("OwnerPassport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessLicenses", Order=4)]
        public GetTradeLicenseBasicByEIDPPResponseOwnerDetailsBusinessLicenses[] BusinessLicenses {
            get {
                return this.businessLicensesField;
            }
            set {
                this.businessLicensesField = value;
                this.RaisePropertyChanged("BusinessLicenses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.informatica.com/dis/ws/")]
    public partial class GetTradeLicenseBasicByEIDPPResponseOwnerDetailsBusinessLicenses : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string licenseNumberField;
        
        private string businessNameArField;
        
        private string businessNameEnField;
        
        private string economicDepartmentARField;
        
        private string economicDepartmentENField;
        
        private string emirateARField;
        
        private string emirateENField;
        
        private string licenseRegistrationDateField;
        
        private string licenseExpiryDateField;
        
        private string licenseStatusARField;
        
        private string licenseStatusENField;
        
        private string licenseFCRNumberField;
        
        private GetTradeLicenseBasicByEIDPPResponseOwnerDetailsBusinessLicensesOwnerPartnership[] ownerPartnershipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LicenseNumber {
            get {
                return this.licenseNumberField;
            }
            set {
                this.licenseNumberField = value;
                this.RaisePropertyChanged("LicenseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusinessNameAr {
            get {
                return this.businessNameArField;
            }
            set {
                this.businessNameArField = value;
                this.RaisePropertyChanged("BusinessNameAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BusinessNameEn {
            get {
                return this.businessNameEnField;
            }
            set {
                this.businessNameEnField = value;
                this.RaisePropertyChanged("BusinessNameEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EconomicDepartmentAR {
            get {
                return this.economicDepartmentARField;
            }
            set {
                this.economicDepartmentARField = value;
                this.RaisePropertyChanged("EconomicDepartmentAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EconomicDepartmentEN {
            get {
                return this.economicDepartmentENField;
            }
            set {
                this.economicDepartmentENField = value;
                this.RaisePropertyChanged("EconomicDepartmentEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EmirateAR {
            get {
                return this.emirateARField;
            }
            set {
                this.emirateARField = value;
                this.RaisePropertyChanged("EmirateAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EmirateEN {
            get {
                return this.emirateENField;
            }
            set {
                this.emirateENField = value;
                this.RaisePropertyChanged("EmirateEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LicenseRegistrationDate {
            get {
                return this.licenseRegistrationDateField;
            }
            set {
                this.licenseRegistrationDateField = value;
                this.RaisePropertyChanged("LicenseRegistrationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LicenseExpiryDate {
            get {
                return this.licenseExpiryDateField;
            }
            set {
                this.licenseExpiryDateField = value;
                this.RaisePropertyChanged("LicenseExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LicenseStatusAR {
            get {
                return this.licenseStatusARField;
            }
            set {
                this.licenseStatusARField = value;
                this.RaisePropertyChanged("LicenseStatusAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LicenseStatusEN {
            get {
                return this.licenseStatusENField;
            }
            set {
                this.licenseStatusENField = value;
                this.RaisePropertyChanged("LicenseStatusEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LicenseFCRNumber {
            get {
                return this.licenseFCRNumberField;
            }
            set {
                this.licenseFCRNumberField = value;
                this.RaisePropertyChanged("LicenseFCRNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OwnerPartnership", Order=12)]
        public GetTradeLicenseBasicByEIDPPResponseOwnerDetailsBusinessLicensesOwnerPartnership[] OwnerPartnership {
            get {
                return this.ownerPartnershipField;
            }
            set {
                this.ownerPartnershipField = value;
                this.RaisePropertyChanged("OwnerPartnership");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.informatica.com/dis/ws/")]
    public partial class GetTradeLicenseBasicByEIDPPResponseOwnerDetailsBusinessLicensesOwnerPartnership : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ownerPartnershipTypeARField;
        
        private string ownerPartnershipTypeENField;
        
        private string ownerSharePercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OwnerPartnershipTypeAR {
            get {
                return this.ownerPartnershipTypeARField;
            }
            set {
                this.ownerPartnershipTypeARField = value;
                this.RaisePropertyChanged("OwnerPartnershipTypeAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OwnerPartnershipTypeEN {
            get {
                return this.ownerPartnershipTypeENField;
            }
            set {
                this.ownerPartnershipTypeENField = value;
                this.RaisePropertyChanged("OwnerPartnershipTypeEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OwnerSharePercentage {
            get {
                return this.ownerSharePercentageField;
            }
            set {
                this.ownerSharePercentageField = value;
                this.RaisePropertyChanged("OwnerSharePercentage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.informatica.com/dis/ws/")]
    public partial class GetTradeLicenseBasicByEIDPPResponseError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inputParametersField;
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InputParameters {
            get {
                return this.inputParametersField;
            }
            set {
                this.inputParametersField = value;
                this.RaisePropertyChanged("InputParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTradeLicenseBasicByEIDPP_Input {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.informatica.com/dis/ws/", Order=0)]
        public MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP GetTradeLicenseBasicByEIDPP;
        
        public GetTradeLicenseBasicByEIDPP_Input() {
        }
        
        public GetTradeLicenseBasicByEIDPP_Input(MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP GetTradeLicenseBasicByEIDPP) {
            this.GetTradeLicenseBasicByEIDPP = GetTradeLicenseBasicByEIDPP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTradeLicenseBasicByEIDPP_Output {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.informatica.com/dis/ws/", Order=0)]
        public MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPPResponse GetTradeLicenseBasicByEIDPPResponse;
        
        public GetTradeLicenseBasicByEIDPP_Output() {
        }
        
        public GetTradeLicenseBasicByEIDPP_Output(MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPPResponse GetTradeLicenseBasicByEIDPPResponse) {
            this.GetTradeLicenseBasicByEIDPPResponse = GetTradeLicenseBasicByEIDPPResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MOE_getTradeLicenseBasicByEIDPPPortTypeChannel : MOCDIntegrations.MoEcService.MOE_getTradeLicenseBasicByEIDPPPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MOE_getTradeLicenseBasicByEIDPPPortTypeClient : System.ServiceModel.ClientBase<MOCDIntegrations.MoEcService.MOE_getTradeLicenseBasicByEIDPPPortType>, MOCDIntegrations.MoEcService.MOE_getTradeLicenseBasicByEIDPPPortType {
        
        public MOE_getTradeLicenseBasicByEIDPPPortTypeClient() {
        }
        
        public MOE_getTradeLicenseBasicByEIDPPPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MOE_getTradeLicenseBasicByEIDPPPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MOE_getTradeLicenseBasicByEIDPPPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MOE_getTradeLicenseBasicByEIDPPPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Output MOCDIntegrations.MoEcService.MOE_getTradeLicenseBasicByEIDPPPortType.GetTradeLicenseBasicByEIDPP(MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Input request) {
            return base.Channel.GetTradeLicenseBasicByEIDPP(request);
        }
        
        public MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPPResponse GetTradeLicenseBasicByEIDPP(MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP GetTradeLicenseBasicByEIDPP1) {
            MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Input inValue = new MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Input();
            inValue.GetTradeLicenseBasicByEIDPP = GetTradeLicenseBasicByEIDPP1;
            MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Output retVal = ((MOCDIntegrations.MoEcService.MOE_getTradeLicenseBasicByEIDPPPortType)(this)).GetTradeLicenseBasicByEIDPP(inValue);
            return retVal.GetTradeLicenseBasicByEIDPPResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Output> MOCDIntegrations.MoEcService.MOE_getTradeLicenseBasicByEIDPPPortType.GetTradeLicenseBasicByEIDPPAsync(MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Input request) {
            return base.Channel.GetTradeLicenseBasicByEIDPPAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Output> GetTradeLicenseBasicByEIDPPAsync(MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP GetTradeLicenseBasicByEIDPP) {
            MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Input inValue = new MOCDIntegrations.MoEcService.GetTradeLicenseBasicByEIDPP_Input();
            inValue.GetTradeLicenseBasicByEIDPP = GetTradeLicenseBasicByEIDPP;
            return ((MOCDIntegrations.MoEcService.MOE_getTradeLicenseBasicByEIDPPPortType)(this)).GetTradeLicenseBasicByEIDPPAsync(inValue);
        }
    }
}
