//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCDIntegrations.SDTPSVS2019 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.esi.dtps.gov.ae/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.esi.dtps.gov.ae/")]
    public partial class attachmentTypeVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activeField;
        
        private bool activeFieldSpecified;
        
        private string attachmentTypeArField;
        
        private string attachmentTypeEnField;
        
        private int attachmentTypeIdField;
        
        private bool attachmentTypeIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string attachmentTypeAr {
            get {
                return this.attachmentTypeArField;
            }
            set {
                this.attachmentTypeArField = value;
                this.RaisePropertyChanged("attachmentTypeAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string attachmentTypeEn {
            get {
                return this.attachmentTypeEnField;
            }
            set {
                this.attachmentTypeEnField = value;
                this.RaisePropertyChanged("attachmentTypeEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int attachmentTypeId {
            get {
                return this.attachmentTypeIdField;
            }
            set {
                this.attachmentTypeIdField = value;
                this.RaisePropertyChanged("attachmentTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentTypeIdSpecified {
            get {
                return this.attachmentTypeIdFieldSpecified;
            }
            set {
                this.attachmentTypeIdFieldSpecified = value;
                this.RaisePropertyChanged("attachmentTypeIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integration.esi.dtps.gov.ae/", ConfigurationName="SDTPSVS2019.DhIntegrationServicePortType")]
    public interface DhIntegrationServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.SDTPSVS2019.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDResponse getAttachmentTypeByID(MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDResponse> getAttachmentTypeByIDAsync(MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.SDTPSVS2019.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListResponse getAttachmentTypesList(MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListResponse> getAttachmentTypesListAsync(MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.SDTPSVS2019.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrResponse createGrantedPlotLetterTr(MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrResponse> createGrantedPlotLetterTrAsync(MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.SDTPSVS2019.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MOCDIntegrations.SDTPSVS2019.getStatusListResponse getStatusList(MOCDIntegrations.SDTPSVS2019.getStatusListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getStatusListResponse> getStatusListAsync(MOCDIntegrations.SDTPSVS2019.getStatusListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.SDTPSVS2019.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MOCDIntegrations.SDTPSVS2019.getBranchesListResponse getBranchesList(MOCDIntegrations.SDTPSVS2019.getBranchesListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getBranchesListResponse> getBranchesListAsync(MOCDIntegrations.SDTPSVS2019.getBranchesListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.SDTPSVS2019.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MOCDIntegrations.SDTPSVS2019.getStatusByIDResponse getStatusByID(MOCDIntegrations.SDTPSVS2019.getStatusByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getStatusByIDResponse> getStatusByIDAsync(MOCDIntegrations.SDTPSVS2019.getStatusByIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.SDTPSVS2019.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MOCDIntegrations.SDTPSVS2019.getFinalProductStatusResponse getFinalProductStatus(MOCDIntegrations.SDTPSVS2019.getFinalProductStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getFinalProductStatusResponse> getFinalProductStatusAsync(MOCDIntegrations.SDTPSVS2019.getFinalProductStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttachmentTypeByID", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getAttachmentTypeByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int attachmentTypeId;
        
        public getAttachmentTypeByIDRequest() {
        }
        
        public getAttachmentTypeByIDRequest(int attachmentTypeId) {
            this.attachmentTypeId = attachmentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttachmentTypeByIDResponse", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getAttachmentTypeByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MOCDIntegrations.SDTPSVS2019.attachmentTypeVO[] @return;
        
        public getAttachmentTypeByIDResponse() {
        }
        
        public getAttachmentTypeByIDResponse(MOCDIntegrations.SDTPSVS2019.attachmentTypeVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttachmentTypesList", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getAttachmentTypesListRequest {
        
        public getAttachmentTypesListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttachmentTypesListResponse", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getAttachmentTypesListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MOCDIntegrations.SDTPSVS2019.attachmentTypeVO[] @return;
        
        public getAttachmentTypesListResponse() {
        }
        
        public getAttachmentTypesListResponse(MOCDIntegrations.SDTPSVS2019.attachmentTypeVO[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.esi.dtps.gov.ae/")]
    public partial class grantPlotLetterVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double amountField;
        
        private bool amountFieldSpecified;
        
        private attachmentVO[] attachementsField;
        
        private string beneficiaryIdField;
        
        private string beneficiaryNameField;
        
        private string branchCodeField;
        
        private string courtLegacyNoField;
        
        private string courtLetterDateField;
        
        private string courtLetterNoField;
        
        private string dobField;
        
        private string emailField;
        
        private string familyNoField;
        
        private string genderField;
        
        private int isGplDetailsField;
        
        private bool isGplDetailsFieldSpecified;
        
        private string kholasetAlqaidIdField;
        
        private string mobileNumberField;
        
        private string nationalityField;
        
        private string orderVoucherNoField;
        
        private string passportNoField;
        
        private gplPlotsDetailsVO[] plotListField;
        
        private string receiptDateField;
        
        private string receiptNoField;
        
        private string receiverIdField;
        
        private string townNoField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachements", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public attachmentVO[] attachements {
            get {
                return this.attachementsField;
            }
            set {
                this.attachementsField = value;
                this.RaisePropertyChanged("attachements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string beneficiaryId {
            get {
                return this.beneficiaryIdField;
            }
            set {
                this.beneficiaryIdField = value;
                this.RaisePropertyChanged("beneficiaryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string beneficiaryName {
            get {
                return this.beneficiaryNameField;
            }
            set {
                this.beneficiaryNameField = value;
                this.RaisePropertyChanged("beneficiaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("branchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string courtLegacyNo {
            get {
                return this.courtLegacyNoField;
            }
            set {
                this.courtLegacyNoField = value;
                this.RaisePropertyChanged("courtLegacyNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string courtLetterDate {
            get {
                return this.courtLetterDateField;
            }
            set {
                this.courtLetterDateField = value;
                this.RaisePropertyChanged("courtLetterDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string courtLetterNo {
            get {
                return this.courtLetterNoField;
            }
            set {
                this.courtLetterNoField = value;
                this.RaisePropertyChanged("courtLetterNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
                this.RaisePropertyChanged("dob");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string familyNo {
            get {
                return this.familyNoField;
            }
            set {
                this.familyNoField = value;
                this.RaisePropertyChanged("familyNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int isGplDetails {
            get {
                return this.isGplDetailsField;
            }
            set {
                this.isGplDetailsField = value;
                this.RaisePropertyChanged("isGplDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isGplDetailsSpecified {
            get {
                return this.isGplDetailsFieldSpecified;
            }
            set {
                this.isGplDetailsFieldSpecified = value;
                this.RaisePropertyChanged("isGplDetailsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string kholasetAlqaidId {
            get {
                return this.kholasetAlqaidIdField;
            }
            set {
                this.kholasetAlqaidIdField = value;
                this.RaisePropertyChanged("kholasetAlqaidId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string mobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("mobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string orderVoucherNo {
            get {
                return this.orderVoucherNoField;
            }
            set {
                this.orderVoucherNoField = value;
                this.RaisePropertyChanged("orderVoucherNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string passportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
                this.RaisePropertyChanged("passportNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plotList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public gplPlotsDetailsVO[] plotList {
            get {
                return this.plotListField;
            }
            set {
                this.plotListField = value;
                this.RaisePropertyChanged("plotList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string receiptDate {
            get {
                return this.receiptDateField;
            }
            set {
                this.receiptDateField = value;
                this.RaisePropertyChanged("receiptDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string receiptNo {
            get {
                return this.receiptNoField;
            }
            set {
                this.receiptNoField = value;
                this.RaisePropertyChanged("receiptNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string receiverId {
            get {
                return this.receiverIdField;
            }
            set {
                this.receiverIdField = value;
                this.RaisePropertyChanged("receiverId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string townNo {
            get {
                return this.townNoField;
            }
            set {
                this.townNoField = value;
                this.RaisePropertyChanged("townNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.esi.dtps.gov.ae/")]
    public partial class attachmentVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activeField;
        
        private bool activeFieldSpecified;
        
        private int attachmentTypeIdField;
        
        private bool attachmentTypeIdFieldSpecified;
        
        private byte[] contentField;
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private string fileNameField;
        
        private string fileURLField;
        
        private string mimeTypeField;
        
        private decimal serialField;
        
        private bool serialFieldSpecified;
        
        private string trxNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int attachmentTypeId {
            get {
                return this.attachmentTypeIdField;
            }
            set {
                this.attachmentTypeIdField = value;
                this.RaisePropertyChanged("attachmentTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentTypeIdSpecified {
            get {
                return this.attachmentTypeIdFieldSpecified;
            }
            set {
                this.attachmentTypeIdFieldSpecified = value;
                this.RaisePropertyChanged("attachmentTypeIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
                this.RaisePropertyChanged("expiryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fileURL {
            get {
                return this.fileURLField;
            }
            set {
                this.fileURLField = value;
                this.RaisePropertyChanged("fileURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serialSpecified {
            get {
                return this.serialFieldSpecified;
            }
            set {
                this.serialFieldSpecified = value;
                this.RaisePropertyChanged("serialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string trxNo {
            get {
                return this.trxNoField;
            }
            set {
                this.trxNoField = value;
                this.RaisePropertyChanged("trxNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.esi.dtps.gov.ae/")]
    public partial class gplPlotsDetailsVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int areaCodeField;
        
        private bool areaCodeFieldSpecified;
        
        private int cityCodeField;
        
        private bool cityCodeFieldSpecified;
        
        private string govNumField;
        
        private string grantDateField;
        
        private int landUsageIdField;
        
        private bool landUsageIdFieldSpecified;
        
        private string remarksField;
        
        private int suburbCodeField;
        
        private bool suburbCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int areaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
                this.RaisePropertyChanged("areaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaCodeSpecified {
            get {
                return this.areaCodeFieldSpecified;
            }
            set {
                this.areaCodeFieldSpecified = value;
                this.RaisePropertyChanged("areaCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cityCodeSpecified {
            get {
                return this.cityCodeFieldSpecified;
            }
            set {
                this.cityCodeFieldSpecified = value;
                this.RaisePropertyChanged("cityCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string govNum {
            get {
                return this.govNumField;
            }
            set {
                this.govNumField = value;
                this.RaisePropertyChanged("govNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string grantDate {
            get {
                return this.grantDateField;
            }
            set {
                this.grantDateField = value;
                this.RaisePropertyChanged("grantDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int landUsageId {
            get {
                return this.landUsageIdField;
            }
            set {
                this.landUsageIdField = value;
                this.RaisePropertyChanged("landUsageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool landUsageIdSpecified {
            get {
                return this.landUsageIdFieldSpecified;
            }
            set {
                this.landUsageIdFieldSpecified = value;
                this.RaisePropertyChanged("landUsageIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int suburbCode {
            get {
                return this.suburbCodeField;
            }
            set {
                this.suburbCodeField = value;
                this.RaisePropertyChanged("suburbCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool suburbCodeSpecified {
            get {
                return this.suburbCodeFieldSpecified;
            }
            set {
                this.suburbCodeFieldSpecified = value;
                this.RaisePropertyChanged("suburbCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createGrantedPlotLetterTr", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class createGrantedPlotLetterTrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MOCDIntegrations.SDTPSVS2019.grantPlotLetterVO grantPlotLetterDetails;
        
        public createGrantedPlotLetterTrRequest() {
        }
        
        public createGrantedPlotLetterTrRequest(MOCDIntegrations.SDTPSVS2019.grantPlotLetterVO grantPlotLetterDetails) {
            this.grantPlotLetterDetails = grantPlotLetterDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createGrantedPlotLetterTrResponse", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class createGrantedPlotLetterTrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public createGrantedPlotLetterTrResponse() {
        }
        
        public createGrantedPlotLetterTrResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.esi.dtps.gov.ae/")]
    public partial class statusVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activeField;
        
        private bool activeFieldSpecified;
        
        private int statusIdField;
        
        private bool statusIdFieldSpecified;
        
        private string statusNameArField;
        
        private string statusNameEnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int statusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("statusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusIdSpecified {
            get {
                return this.statusIdFieldSpecified;
            }
            set {
                this.statusIdFieldSpecified = value;
                this.RaisePropertyChanged("statusIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusNameAr {
            get {
                return this.statusNameArField;
            }
            set {
                this.statusNameArField = value;
                this.RaisePropertyChanged("statusNameAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string statusNameEn {
            get {
                return this.statusNameEnField;
            }
            set {
                this.statusNameEnField = value;
                this.RaisePropertyChanged("statusNameEn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusList", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getStatusListRequest {
        
        public getStatusListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusListResponse", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getStatusListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MOCDIntegrations.SDTPSVS2019.statusVO[] @return;
        
        public getStatusListResponse() {
        }
        
        public getStatusListResponse(MOCDIntegrations.SDTPSVS2019.statusVO[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.esi.dtps.gov.ae/")]
    public partial class branchVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activeField;
        
        private bool activeFieldSpecified;
        
        private int branchIdField;
        
        private bool branchIdFieldSpecified;
        
        private string branchNameArField;
        
        private string branchNameEnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int branchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
                this.RaisePropertyChanged("branchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool branchIdSpecified {
            get {
                return this.branchIdFieldSpecified;
            }
            set {
                this.branchIdFieldSpecified = value;
                this.RaisePropertyChanged("branchIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string branchNameAr {
            get {
                return this.branchNameArField;
            }
            set {
                this.branchNameArField = value;
                this.RaisePropertyChanged("branchNameAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string branchNameEn {
            get {
                return this.branchNameEnField;
            }
            set {
                this.branchNameEnField = value;
                this.RaisePropertyChanged("branchNameEn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBranchesList", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getBranchesListRequest {
        
        public getBranchesListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBranchesListResponse", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getBranchesListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MOCDIntegrations.SDTPSVS2019.branchVO[] @return;
        
        public getBranchesListResponse() {
        }
        
        public getBranchesListResponse(MOCDIntegrations.SDTPSVS2019.branchVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusByID", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getStatusByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int statusId;
        
        public getStatusByIDRequest() {
        }
        
        public getStatusByIDRequest(int statusId) {
            this.statusId = statusId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusByIDResponse", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getStatusByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MOCDIntegrations.SDTPSVS2019.statusVO[] @return;
        
        public getStatusByIDResponse() {
        }
        
        public getStatusByIDResponse(MOCDIntegrations.SDTPSVS2019.statusVO[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.esi.dtps.gov.ae/")]
    public partial class finalProductVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] contentField;
        
        private string rejectedRemarksField;
        
        private int statusIdField;
        
        private bool statusIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rejectedRemarks {
            get {
                return this.rejectedRemarksField;
            }
            set {
                this.rejectedRemarksField = value;
                this.RaisePropertyChanged("rejectedRemarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int statusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("statusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusIdSpecified {
            get {
                return this.statusIdFieldSpecified;
            }
            set {
                this.statusIdFieldSpecified = value;
                this.RaisePropertyChanged("statusIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFinalProductStatus", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getFinalProductStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionNumber;
        
        public getFinalProductStatusRequest() {
        }
        
        public getFinalProductStatusRequest(string transactionNumber) {
            this.transactionNumber = transactionNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFinalProductStatusResponse", WrapperNamespace="http://integration.esi.dtps.gov.ae/", IsWrapped=true)]
    public partial class getFinalProductStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integration.esi.dtps.gov.ae/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MOCDIntegrations.SDTPSVS2019.finalProductVO @return;
        
        public getFinalProductStatusResponse() {
        }
        
        public getFinalProductStatusResponse(MOCDIntegrations.SDTPSVS2019.finalProductVO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DhIntegrationServicePortTypeChannel : MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DhIntegrationServicePortTypeClient : System.ServiceModel.ClientBase<MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType>, MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType {
        
        public DhIntegrationServicePortTypeClient() {
        }
        
        public DhIntegrationServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DhIntegrationServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DhIntegrationServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DhIntegrationServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDResponse MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getAttachmentTypeByID(MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDRequest request) {
            return base.Channel.getAttachmentTypeByID(request);
        }
        
        public MOCDIntegrations.SDTPSVS2019.attachmentTypeVO[] getAttachmentTypeByID(int attachmentTypeId) {
            MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDRequest inValue = new MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDRequest();
            inValue.attachmentTypeId = attachmentTypeId;
            MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDResponse retVal = ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getAttachmentTypeByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDResponse> MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getAttachmentTypeByIDAsync(MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDRequest request) {
            return base.Channel.getAttachmentTypeByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDResponse> getAttachmentTypeByIDAsync(int attachmentTypeId) {
            MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDRequest inValue = new MOCDIntegrations.SDTPSVS2019.getAttachmentTypeByIDRequest();
            inValue.attachmentTypeId = attachmentTypeId;
            return ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getAttachmentTypeByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListResponse MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getAttachmentTypesList(MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListRequest request) {
            return base.Channel.getAttachmentTypesList(request);
        }
        
        public MOCDIntegrations.SDTPSVS2019.attachmentTypeVO[] getAttachmentTypesList() {
            MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListRequest inValue = new MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListRequest();
            MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListResponse retVal = ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getAttachmentTypesList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListResponse> MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getAttachmentTypesListAsync(MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListRequest request) {
            return base.Channel.getAttachmentTypesListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListResponse> getAttachmentTypesListAsync() {
            MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListRequest inValue = new MOCDIntegrations.SDTPSVS2019.getAttachmentTypesListRequest();
            return ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getAttachmentTypesListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrResponse MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.createGrantedPlotLetterTr(MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrRequest request) {
            return base.Channel.createGrantedPlotLetterTr(request);
        }
        
        public string createGrantedPlotLetterTr(MOCDIntegrations.SDTPSVS2019.grantPlotLetterVO grantPlotLetterDetails) {
            MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrRequest inValue = new MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrRequest();
            inValue.grantPlotLetterDetails = grantPlotLetterDetails;
            MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrResponse retVal = ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).createGrantedPlotLetterTr(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrResponse> MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.createGrantedPlotLetterTrAsync(MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrRequest request) {
            return base.Channel.createGrantedPlotLetterTrAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrResponse> createGrantedPlotLetterTrAsync(MOCDIntegrations.SDTPSVS2019.grantPlotLetterVO grantPlotLetterDetails) {
            MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrRequest inValue = new MOCDIntegrations.SDTPSVS2019.createGrantedPlotLetterTrRequest();
            inValue.grantPlotLetterDetails = grantPlotLetterDetails;
            return ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).createGrantedPlotLetterTrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.SDTPSVS2019.getStatusListResponse MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getStatusList(MOCDIntegrations.SDTPSVS2019.getStatusListRequest request) {
            return base.Channel.getStatusList(request);
        }
        
        public MOCDIntegrations.SDTPSVS2019.statusVO[] getStatusList() {
            MOCDIntegrations.SDTPSVS2019.getStatusListRequest inValue = new MOCDIntegrations.SDTPSVS2019.getStatusListRequest();
            MOCDIntegrations.SDTPSVS2019.getStatusListResponse retVal = ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getStatusList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getStatusListResponse> MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getStatusListAsync(MOCDIntegrations.SDTPSVS2019.getStatusListRequest request) {
            return base.Channel.getStatusListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getStatusListResponse> getStatusListAsync() {
            MOCDIntegrations.SDTPSVS2019.getStatusListRequest inValue = new MOCDIntegrations.SDTPSVS2019.getStatusListRequest();
            return ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getStatusListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.SDTPSVS2019.getBranchesListResponse MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getBranchesList(MOCDIntegrations.SDTPSVS2019.getBranchesListRequest request) {
            return base.Channel.getBranchesList(request);
        }
        
        public MOCDIntegrations.SDTPSVS2019.branchVO[] getBranchesList() {
            MOCDIntegrations.SDTPSVS2019.getBranchesListRequest inValue = new MOCDIntegrations.SDTPSVS2019.getBranchesListRequest();
            MOCDIntegrations.SDTPSVS2019.getBranchesListResponse retVal = ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getBranchesList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getBranchesListResponse> MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getBranchesListAsync(MOCDIntegrations.SDTPSVS2019.getBranchesListRequest request) {
            return base.Channel.getBranchesListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getBranchesListResponse> getBranchesListAsync() {
            MOCDIntegrations.SDTPSVS2019.getBranchesListRequest inValue = new MOCDIntegrations.SDTPSVS2019.getBranchesListRequest();
            return ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getBranchesListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.SDTPSVS2019.getStatusByIDResponse MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getStatusByID(MOCDIntegrations.SDTPSVS2019.getStatusByIDRequest request) {
            return base.Channel.getStatusByID(request);
        }
        
        public MOCDIntegrations.SDTPSVS2019.statusVO[] getStatusByID(int statusId) {
            MOCDIntegrations.SDTPSVS2019.getStatusByIDRequest inValue = new MOCDIntegrations.SDTPSVS2019.getStatusByIDRequest();
            inValue.statusId = statusId;
            MOCDIntegrations.SDTPSVS2019.getStatusByIDResponse retVal = ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getStatusByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getStatusByIDResponse> MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getStatusByIDAsync(MOCDIntegrations.SDTPSVS2019.getStatusByIDRequest request) {
            return base.Channel.getStatusByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getStatusByIDResponse> getStatusByIDAsync(int statusId) {
            MOCDIntegrations.SDTPSVS2019.getStatusByIDRequest inValue = new MOCDIntegrations.SDTPSVS2019.getStatusByIDRequest();
            inValue.statusId = statusId;
            return ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getStatusByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.SDTPSVS2019.getFinalProductStatusResponse MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getFinalProductStatus(MOCDIntegrations.SDTPSVS2019.getFinalProductStatusRequest request) {
            return base.Channel.getFinalProductStatus(request);
        }
        
        public MOCDIntegrations.SDTPSVS2019.finalProductVO getFinalProductStatus(string transactionNumber) {
            MOCDIntegrations.SDTPSVS2019.getFinalProductStatusRequest inValue = new MOCDIntegrations.SDTPSVS2019.getFinalProductStatusRequest();
            inValue.transactionNumber = transactionNumber;
            MOCDIntegrations.SDTPSVS2019.getFinalProductStatusResponse retVal = ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getFinalProductStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getFinalProductStatusResponse> MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType.getFinalProductStatusAsync(MOCDIntegrations.SDTPSVS2019.getFinalProductStatusRequest request) {
            return base.Channel.getFinalProductStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.SDTPSVS2019.getFinalProductStatusResponse> getFinalProductStatusAsync(string transactionNumber) {
            MOCDIntegrations.SDTPSVS2019.getFinalProductStatusRequest inValue = new MOCDIntegrations.SDTPSVS2019.getFinalProductStatusRequest();
            inValue.transactionNumber = transactionNumber;
            return ((MOCDIntegrations.SDTPSVS2019.DhIntegrationServicePortType)(this)).getFinalProductStatusAsync(inValue);
        }
    }
}
