//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCDIntegrations.MoIService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema")]
    public partial class ErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string typeField;
        
        private string arDescField;
        
        private string enDescField;
        
        private string refNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string arDesc {
            get {
                return this.arDescField;
            }
            set {
                this.arDescField = value;
                this.RaisePropertyChanged("arDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string enDesc {
            get {
                return this.enDescField;
            }
            set {
                this.enDescField = value;
                this.RaisePropertyChanged("enDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string refNumber {
            get {
                return this.refNumberField;
            }
            set {
                this.refNumberField = value;
                this.RaisePropertyChanged("refNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema")]
    public partial class LookupType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> idField;
        
        private bool idFieldSpecified;
        
        private string arDescField;
        
        private string enDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string arDesc {
            get {
                return this.arDescField;
            }
            set {
                this.arDescField = value;
                this.RaisePropertyChanged("arDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string enDesc {
            get {
                return this.enDescField;
            }
            set {
                this.enDescField = value;
                this.RaisePropertyChanged("enDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema")]
    public partial class PersonCIDetailsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> isPersonHasBeenImprisonedField;
        
        private bool isPersonHasBeenImprisonedFieldSpecified;
        
        private LookupType personCertificateStatusField;
        
        private System.Nullable<bool> isPersonHasTreatmentField;
        
        private bool isPersonHasTreatmentFieldSpecified;
        
        private System.Nullable<bool> isPersonExitCountryField;
        
        private bool isPersonExitCountryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> isPersonHasBeenImprisoned {
            get {
                return this.isPersonHasBeenImprisonedField;
            }
            set {
                this.isPersonHasBeenImprisonedField = value;
                this.RaisePropertyChanged("isPersonHasBeenImprisoned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isPersonHasBeenImprisonedSpecified {
            get {
                return this.isPersonHasBeenImprisonedFieldSpecified;
            }
            set {
                this.isPersonHasBeenImprisonedFieldSpecified = value;
                this.RaisePropertyChanged("isPersonHasBeenImprisonedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public LookupType personCertificateStatus {
            get {
                return this.personCertificateStatusField;
            }
            set {
                this.personCertificateStatusField = value;
                this.RaisePropertyChanged("personCertificateStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> isPersonHasTreatment {
            get {
                return this.isPersonHasTreatmentField;
            }
            set {
                this.isPersonHasTreatmentField = value;
                this.RaisePropertyChanged("isPersonHasTreatment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isPersonHasTreatmentSpecified {
            get {
                return this.isPersonHasTreatmentFieldSpecified;
            }
            set {
                this.isPersonHasTreatmentFieldSpecified = value;
                this.RaisePropertyChanged("isPersonHasTreatmentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> isPersonExitCountry {
            get {
                return this.isPersonExitCountryField;
            }
            set {
                this.isPersonExitCountryField = value;
                this.RaisePropertyChanged("isPersonExitCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isPersonExitCountrySpecified {
            get {
                return this.isPersonExitCountryFieldSpecified;
            }
            set {
                this.isPersonExitCountryFieldSpecified = value;
                this.RaisePropertyChanged("isPersonExitCountrySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema")]
    public partial class InquiryCriteriaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identityCardNumber", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("unifiedNumber", typeof(long), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.moi.gov.ae/2017/MOIServices/PersonCIInquiry", ConfigurationName="MoIService.personCIInquiry_ptt")]
    public interface personCIInquiry_ptt {
        
        // CODEGEN: Generating message contract since the operation getPersonCIDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getPersonCIDetails", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.MoIService.ErrorType), Action="getPersonCIDetails", Name="error", Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MOCDIntegrations.MoIService.getPersonCIDetailsResponse getPersonCIDetails(MOCDIntegrations.MoIService.getPersonCIDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getPersonCIDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.MoIService.getPersonCIDetailsResponse> getPersonCIDetailsAsync(MOCDIntegrations.MoIService.getPersonCIDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema")]
    public partial class TrnHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdField;
        
        private string serviceProviderEntityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string serviceProviderEntity {
            get {
                return this.serviceProviderEntityField;
            }
            set {
                this.serviceProviderEntityField = value;
                this.RaisePropertyChanged("serviceProviderEntity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonCIDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema")]
        public MOCDIntegrations.MoIService.TrnHeaderType TrnHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema", Order=0)]
        public MOCDIntegrations.MoIService.InquiryCriteriaType inquiryCriteria;
        
        public getPersonCIDetailsRequest() {
        }
        
        public getPersonCIDetailsRequest(MOCDIntegrations.MoIService.TrnHeaderType TrnHeader, MOCDIntegrations.MoIService.InquiryCriteriaType inquiryCriteria) {
            this.TrnHeader = TrnHeader;
            this.inquiryCriteria = inquiryCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonCIDetailsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema")]
        public MOCDIntegrations.MoIService.TrnHeaderType TrnHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.moi.gov.ae/2017/MOIServices/PersonCIInquirySchema", Order=0)]
        public MOCDIntegrations.MoIService.PersonCIDetailsType personCIDetails;
        
        public getPersonCIDetailsResponse() {
        }
        
        public getPersonCIDetailsResponse(MOCDIntegrations.MoIService.TrnHeaderType TrnHeader, MOCDIntegrations.MoIService.PersonCIDetailsType personCIDetails) {
            this.TrnHeader = TrnHeader;
            this.personCIDetails = personCIDetails;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface personCIInquiry_pttChannel : MOCDIntegrations.MoIService.personCIInquiry_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class personCIInquiry_pttClient : System.ServiceModel.ClientBase<MOCDIntegrations.MoIService.personCIInquiry_ptt>, MOCDIntegrations.MoIService.personCIInquiry_ptt {
        
        public personCIInquiry_pttClient() {
        }
        
        public personCIInquiry_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public personCIInquiry_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public personCIInquiry_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public personCIInquiry_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.MoIService.getPersonCIDetailsResponse MOCDIntegrations.MoIService.personCIInquiry_ptt.getPersonCIDetails(MOCDIntegrations.MoIService.getPersonCIDetailsRequest request) {
            return base.Channel.getPersonCIDetails(request);
        }
        
        public MOCDIntegrations.MoIService.PersonCIDetailsType getPersonCIDetails(ref MOCDIntegrations.MoIService.TrnHeaderType TrnHeader, MOCDIntegrations.MoIService.InquiryCriteriaType inquiryCriteria) {
            MOCDIntegrations.MoIService.getPersonCIDetailsRequest inValue = new MOCDIntegrations.MoIService.getPersonCIDetailsRequest();
            inValue.TrnHeader = TrnHeader;
            inValue.inquiryCriteria = inquiryCriteria;
            MOCDIntegrations.MoIService.getPersonCIDetailsResponse retVal = ((MOCDIntegrations.MoIService.personCIInquiry_ptt)(this)).getPersonCIDetails(inValue);
            TrnHeader = retVal.TrnHeader;
            return retVal.personCIDetails;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.MoIService.getPersonCIDetailsResponse> MOCDIntegrations.MoIService.personCIInquiry_ptt.getPersonCIDetailsAsync(MOCDIntegrations.MoIService.getPersonCIDetailsRequest request) {
            return base.Channel.getPersonCIDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.MoIService.getPersonCIDetailsResponse> getPersonCIDetailsAsync(MOCDIntegrations.MoIService.TrnHeaderType TrnHeader, MOCDIntegrations.MoIService.InquiryCriteriaType inquiryCriteria) {
            MOCDIntegrations.MoIService.getPersonCIDetailsRequest inValue = new MOCDIntegrations.MoIService.getPersonCIDetailsRequest();
            inValue.TrnHeader = TrnHeader;
            inValue.inquiryCriteria = inquiryCriteria;
            return ((MOCDIntegrations.MoIService.personCIInquiry_ptt)(this)).getPersonCIDetailsAsync(inValue);
        }
    }
}
