//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCDIntegrations.CDAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/CustomUI", ConfigurationName="CDAService.CDA_spcMOCD_spcWSDL_spcWF")]
    public interface CDA_spcMOCD_spcWSDL_spcWF {
        
        // CODEGEN: Generating message contract since the operation CDA_spcMOCD_spcWSDL_spcWF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:CDA_spcMOCD_spcWSDL_spcWF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFResponse CDA_spcMOCD_spcWSDL_spcWF(MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://siebel.com/CustomUI:CDA_spcMOCD_spcWSDL_spcWF", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFResponse> CDA_spcMOCD_spcWSDL_spcWFAsync(MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class CDA_spcMOCD_spcWSDL_spcWF_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string family_NumberField;
        
        private string unified_NumberField;
        
        private string emirates_spcIDField;
        
        private string passportNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Family_Number {
            get {
                return this.family_NumberField;
            }
            set {
                this.family_NumberField = value;
                this.RaisePropertyChanged("Family_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Unified_Number {
            get {
                return this.unified_NumberField;
            }
            set {
                this.unified_NumberField = value;
                this.RaisePropertyChanged("Unified_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Emirates_spcID {
            get {
                return this.emirates_spcIDField;
            }
            set {
                this.emirates_spcIDField = value;
                this.RaisePropertyChanged("Emirates_spcID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PassportNum {
            get {
                return this.passportNumField;
            }
            set {
                this.passportNumField = value;
                this.RaisePropertyChanged("PassportNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://siebel.com/CustomUI")]
    public partial class CDA_spcMOCD_spcWSDL_spcWF_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aid_SourceField;
        
        private string approval_DateField;
        
        private string approvedField;
        
        private string beneficiary_NameField;
        
        private string categoryField;
        
        private string createdDateField;
        
        private string dateofBirthField;
        
        private string dateofDeathField;
        
        private string descriptionField;
        
        private string disbusrsment_StatusField;
        
        private string education_LevelField;
        
        private string error_Message_EmiratesIdField;
        
        private string error_Message_Family_NoField;
        
        private string error_Message_PH_SRField;
        
        private string error_Message_POD_SRField;
        
        private string error_Message_Passport_NoField;
        
        private string error_Message_RFA_SRField;
        
        private string error_Message_TH_spcSRField;
        
        private string error_Message_Unified_NoField;
        
        private string file_NumberField;
        
        private string first_NameField;
        
        private string full_Name_ArabicField;
        
        private string good_Manner_and_Behavior_LetterField;
        
        private string health_SituationField;
        
        private string jobField;
        
        private string makani_NumberField;
        
        private string marital_StatusField;
        
        private string monthly_IncomeField;
        
        private string mother_Name_ArabicField;
        
        private string nationalityField;
        
        private string newField;
        
        private string notesField;
        
        private string number_of_Family_MembersField;
        
        private string pHApprovedField;
        
        private string pHCreatedDateField;
        
        private string pHNewField;
        
        private string pHNotesField;
        
        private string pHSR_pndField;
        
        private string pHStageField;
        
        private string pHStatusField;
        
        private string pH_ReStudyField;
        
        private string pOD_ApprovedField;
        
        private string pOD_Created_DateField;
        
        private string pOD_NewField;
        
        private string pOD_NotesField;
        
        private string pOD_ReStudyField;
        
        private string pOD_SR_pndField;
        
        private string pOD_StageField;
        
        private string pOD_StatusField;
        
        private string pOD_Total_Benefit_ApprovedField;
        
        private string person_is_DeadField;
        
        private string preparingHouseBenefitField;
        
        private string primary_Phone_NumberField;
        
        private string re_StudyField;
        
        private string relation_TypeField;
        
        private string request_StatusField;
        
        private string sR_pndField;
        
        private string stageField;
        
        private string statusField;
        
        private string tH_ApprovedField;
        
        private string tH_Created_DateField;
        
        private string tH_NewField;
        
        private string tH_NotesField;
        
        private string tH_ReStudyField;
        
        private string tH_SR_pndField;
        
        private string tH_StageField;
        
        private string tH_StatusField;
        
        private string tH_Total_Benefit_ApprovedField;
        
        private string total_Benefit_ApprovedField;
        
        private string typeField;
        
        private string typeOfBenefitField;
        
        private string typeOfBenefit_1Field;
        
        private string typeOfBenefit_2Field;
        
        private string typeOfBenefit_3Field;
        
        private string type_of_HousingField;
        
        private string type_of_IncomeField;
        
        private string zoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Aid_Source {
            get {
                return this.aid_SourceField;
            }
            set {
                this.aid_SourceField = value;
                this.RaisePropertyChanged("Aid_Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Approval_Date {
            get {
                return this.approval_DateField;
            }
            set {
                this.approval_DateField = value;
                this.RaisePropertyChanged("Approval_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Approved {
            get {
                return this.approvedField;
            }
            set {
                this.approvedField = value;
                this.RaisePropertyChanged("Approved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Beneficiary_Name {
            get {
                return this.beneficiary_NameField;
            }
            set {
                this.beneficiary_NameField = value;
                this.RaisePropertyChanged("Beneficiary_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DateofBirth {
            get {
                return this.dateofBirthField;
            }
            set {
                this.dateofBirthField = value;
                this.RaisePropertyChanged("DateofBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DateofDeath {
            get {
                return this.dateofDeathField;
            }
            set {
                this.dateofDeathField = value;
                this.RaisePropertyChanged("DateofDeath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Disbusrsment_Status {
            get {
                return this.disbusrsment_StatusField;
            }
            set {
                this.disbusrsment_StatusField = value;
                this.RaisePropertyChanged("Disbusrsment_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Education_Level {
            get {
                return this.education_LevelField;
            }
            set {
                this.education_LevelField = value;
                this.RaisePropertyChanged("Education_Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Error_Message_EmiratesId {
            get {
                return this.error_Message_EmiratesIdField;
            }
            set {
                this.error_Message_EmiratesIdField = value;
                this.RaisePropertyChanged("Error_Message_EmiratesId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Error_Message_Family_No {
            get {
                return this.error_Message_Family_NoField;
            }
            set {
                this.error_Message_Family_NoField = value;
                this.RaisePropertyChanged("Error_Message_Family_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Error_Message_PH_SR {
            get {
                return this.error_Message_PH_SRField;
            }
            set {
                this.error_Message_PH_SRField = value;
                this.RaisePropertyChanged("Error_Message_PH_SR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Error_Message_POD_SR {
            get {
                return this.error_Message_POD_SRField;
            }
            set {
                this.error_Message_POD_SRField = value;
                this.RaisePropertyChanged("Error_Message_POD_SR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Error_Message_Passport_No {
            get {
                return this.error_Message_Passport_NoField;
            }
            set {
                this.error_Message_Passport_NoField = value;
                this.RaisePropertyChanged("Error_Message_Passport_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Error_Message_RFA_SR {
            get {
                return this.error_Message_RFA_SRField;
            }
            set {
                this.error_Message_RFA_SRField = value;
                this.RaisePropertyChanged("Error_Message_RFA_SR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Error_Message_TH_spcSR {
            get {
                return this.error_Message_TH_spcSRField;
            }
            set {
                this.error_Message_TH_spcSRField = value;
                this.RaisePropertyChanged("Error_Message_TH_spcSR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Error_Message_Unified_No {
            get {
                return this.error_Message_Unified_NoField;
            }
            set {
                this.error_Message_Unified_NoField = value;
                this.RaisePropertyChanged("Error_Message_Unified_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string File_Number {
            get {
                return this.file_NumberField;
            }
            set {
                this.file_NumberField = value;
                this.RaisePropertyChanged("File_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string First_Name {
            get {
                return this.first_NameField;
            }
            set {
                this.first_NameField = value;
                this.RaisePropertyChanged("First_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Full_Name_Arabic {
            get {
                return this.full_Name_ArabicField;
            }
            set {
                this.full_Name_ArabicField = value;
                this.RaisePropertyChanged("Full_Name_Arabic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Good_Manner_and_Behavior_Letter {
            get {
                return this.good_Manner_and_Behavior_LetterField;
            }
            set {
                this.good_Manner_and_Behavior_LetterField = value;
                this.RaisePropertyChanged("Good_Manner_and_Behavior_Letter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Health_Situation {
            get {
                return this.health_SituationField;
            }
            set {
                this.health_SituationField = value;
                this.RaisePropertyChanged("Health_Situation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
                this.RaisePropertyChanged("Job");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Makani_Number {
            get {
                return this.makani_NumberField;
            }
            set {
                this.makani_NumberField = value;
                this.RaisePropertyChanged("Makani_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Marital_Status {
            get {
                return this.marital_StatusField;
            }
            set {
                this.marital_StatusField = value;
                this.RaisePropertyChanged("Marital_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Monthly_Income {
            get {
                return this.monthly_IncomeField;
            }
            set {
                this.monthly_IncomeField = value;
                this.RaisePropertyChanged("Monthly_Income");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Mother_Name_Arabic {
            get {
                return this.mother_Name_ArabicField;
            }
            set {
                this.mother_Name_ArabicField = value;
                this.RaisePropertyChanged("Mother_Name_Arabic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string New {
            get {
                return this.newField;
            }
            set {
                this.newField = value;
                this.RaisePropertyChanged("New");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Number_of_Family_Members {
            get {
                return this.number_of_Family_MembersField;
            }
            set {
                this.number_of_Family_MembersField = value;
                this.RaisePropertyChanged("Number_of_Family_Members");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string PHApproved {
            get {
                return this.pHApprovedField;
            }
            set {
                this.pHApprovedField = value;
                this.RaisePropertyChanged("PHApproved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string PHCreatedDate {
            get {
                return this.pHCreatedDateField;
            }
            set {
                this.pHCreatedDateField = value;
                this.RaisePropertyChanged("PHCreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string PHNew {
            get {
                return this.pHNewField;
            }
            set {
                this.pHNewField = value;
                this.RaisePropertyChanged("PHNew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string PHNotes {
            get {
                return this.pHNotesField;
            }
            set {
                this.pHNotesField = value;
                this.RaisePropertyChanged("PHNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string PHSR_pnd {
            get {
                return this.pHSR_pndField;
            }
            set {
                this.pHSR_pndField = value;
                this.RaisePropertyChanged("PHSR_pnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string PHStage {
            get {
                return this.pHStageField;
            }
            set {
                this.pHStageField = value;
                this.RaisePropertyChanged("PHStage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string PHStatus {
            get {
                return this.pHStatusField;
            }
            set {
                this.pHStatusField = value;
                this.RaisePropertyChanged("PHStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string PH_ReStudy {
            get {
                return this.pH_ReStudyField;
            }
            set {
                this.pH_ReStudyField = value;
                this.RaisePropertyChanged("PH_ReStudy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string POD_Approved {
            get {
                return this.pOD_ApprovedField;
            }
            set {
                this.pOD_ApprovedField = value;
                this.RaisePropertyChanged("POD_Approved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string POD_Created_Date {
            get {
                return this.pOD_Created_DateField;
            }
            set {
                this.pOD_Created_DateField = value;
                this.RaisePropertyChanged("POD_Created_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string POD_New {
            get {
                return this.pOD_NewField;
            }
            set {
                this.pOD_NewField = value;
                this.RaisePropertyChanged("POD_New");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string POD_Notes {
            get {
                return this.pOD_NotesField;
            }
            set {
                this.pOD_NotesField = value;
                this.RaisePropertyChanged("POD_Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string POD_ReStudy {
            get {
                return this.pOD_ReStudyField;
            }
            set {
                this.pOD_ReStudyField = value;
                this.RaisePropertyChanged("POD_ReStudy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string POD_SR_pnd {
            get {
                return this.pOD_SR_pndField;
            }
            set {
                this.pOD_SR_pndField = value;
                this.RaisePropertyChanged("POD_SR_pnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string POD_Stage {
            get {
                return this.pOD_StageField;
            }
            set {
                this.pOD_StageField = value;
                this.RaisePropertyChanged("POD_Stage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string POD_Status {
            get {
                return this.pOD_StatusField;
            }
            set {
                this.pOD_StatusField = value;
                this.RaisePropertyChanged("POD_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string POD_Total_Benefit_Approved {
            get {
                return this.pOD_Total_Benefit_ApprovedField;
            }
            set {
                this.pOD_Total_Benefit_ApprovedField = value;
                this.RaisePropertyChanged("POD_Total_Benefit_Approved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string Person_is_Dead {
            get {
                return this.person_is_DeadField;
            }
            set {
                this.person_is_DeadField = value;
                this.RaisePropertyChanged("Person_is_Dead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string PreparingHouseBenefit {
            get {
                return this.preparingHouseBenefitField;
            }
            set {
                this.preparingHouseBenefitField = value;
                this.RaisePropertyChanged("PreparingHouseBenefit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string Primary_Phone_Number {
            get {
                return this.primary_Phone_NumberField;
            }
            set {
                this.primary_Phone_NumberField = value;
                this.RaisePropertyChanged("Primary_Phone_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string Re_Study {
            get {
                return this.re_StudyField;
            }
            set {
                this.re_StudyField = value;
                this.RaisePropertyChanged("Re_Study");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string Relation_Type {
            get {
                return this.relation_TypeField;
            }
            set {
                this.relation_TypeField = value;
                this.RaisePropertyChanged("Relation_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string Request_Status {
            get {
                return this.request_StatusField;
            }
            set {
                this.request_StatusField = value;
                this.RaisePropertyChanged("Request_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string SR_pnd {
            get {
                return this.sR_pndField;
            }
            set {
                this.sR_pndField = value;
                this.RaisePropertyChanged("SR_pnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string Stage {
            get {
                return this.stageField;
            }
            set {
                this.stageField = value;
                this.RaisePropertyChanged("Stage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string TH_Approved {
            get {
                return this.tH_ApprovedField;
            }
            set {
                this.tH_ApprovedField = value;
                this.RaisePropertyChanged("TH_Approved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string TH_Created_Date {
            get {
                return this.tH_Created_DateField;
            }
            set {
                this.tH_Created_DateField = value;
                this.RaisePropertyChanged("TH_Created_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string TH_New {
            get {
                return this.tH_NewField;
            }
            set {
                this.tH_NewField = value;
                this.RaisePropertyChanged("TH_New");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string TH_Notes {
            get {
                return this.tH_NotesField;
            }
            set {
                this.tH_NotesField = value;
                this.RaisePropertyChanged("TH_Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string TH_ReStudy {
            get {
                return this.tH_ReStudyField;
            }
            set {
                this.tH_ReStudyField = value;
                this.RaisePropertyChanged("TH_ReStudy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string TH_SR_pnd {
            get {
                return this.tH_SR_pndField;
            }
            set {
                this.tH_SR_pndField = value;
                this.RaisePropertyChanged("TH_SR_pnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string TH_Stage {
            get {
                return this.tH_StageField;
            }
            set {
                this.tH_StageField = value;
                this.RaisePropertyChanged("TH_Stage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string TH_Status {
            get {
                return this.tH_StatusField;
            }
            set {
                this.tH_StatusField = value;
                this.RaisePropertyChanged("TH_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string TH_Total_Benefit_Approved {
            get {
                return this.tH_Total_Benefit_ApprovedField;
            }
            set {
                this.tH_Total_Benefit_ApprovedField = value;
                this.RaisePropertyChanged("TH_Total_Benefit_Approved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string Total_Benefit_Approved {
            get {
                return this.total_Benefit_ApprovedField;
            }
            set {
                this.total_Benefit_ApprovedField = value;
                this.RaisePropertyChanged("Total_Benefit_Approved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public string TypeOfBenefit {
            get {
                return this.typeOfBenefitField;
            }
            set {
                this.typeOfBenefitField = value;
                this.RaisePropertyChanged("TypeOfBenefit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string TypeOfBenefit_1 {
            get {
                return this.typeOfBenefit_1Field;
            }
            set {
                this.typeOfBenefit_1Field = value;
                this.RaisePropertyChanged("TypeOfBenefit_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string TypeOfBenefit_2 {
            get {
                return this.typeOfBenefit_2Field;
            }
            set {
                this.typeOfBenefit_2Field = value;
                this.RaisePropertyChanged("TypeOfBenefit_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public string TypeOfBenefit_3 {
            get {
                return this.typeOfBenefit_3Field;
            }
            set {
                this.typeOfBenefit_3Field = value;
                this.RaisePropertyChanged("TypeOfBenefit_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string Type_of_Housing {
            get {
                return this.type_of_HousingField;
            }
            set {
                this.type_of_HousingField = value;
                this.RaisePropertyChanged("Type_of_Housing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public string Type_of_Income {
            get {
                return this.type_of_IncomeField;
            }
            set {
                this.type_of_IncomeField = value;
                this.RaisePropertyChanged("Type_of_Income");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public string Zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
                this.RaisePropertyChanged("Zone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CDA_spcMOCD_spcWSDL_spcWFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF_Input CDA_spcMOCD_spcWSDL_spcWF_Input;
        
        public CDA_spcMOCD_spcWSDL_spcWFRequest() {
        }
        
        public CDA_spcMOCD_spcWSDL_spcWFRequest(MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF_Input CDA_spcMOCD_spcWSDL_spcWF_Input) {
            this.CDA_spcMOCD_spcWSDL_spcWF_Input = CDA_spcMOCD_spcWSDL_spcWF_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CDA_spcMOCD_spcWSDL_spcWFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://siebel.com/CustomUI", Order=0)]
        public MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF_Output CDA_spcMOCD_spcWSDL_spcWF_Output;
        
        public CDA_spcMOCD_spcWSDL_spcWFResponse() {
        }
        
        public CDA_spcMOCD_spcWSDL_spcWFResponse(MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF_Output CDA_spcMOCD_spcWSDL_spcWF_Output) {
            this.CDA_spcMOCD_spcWSDL_spcWF_Output = CDA_spcMOCD_spcWSDL_spcWF_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CDA_spcMOCD_spcWSDL_spcWFChannel : MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDA_spcMOCD_spcWSDL_spcWFClient : System.ServiceModel.ClientBase<MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF>, MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF {
        
        public CDA_spcMOCD_spcWSDL_spcWFClient() {
        }
        
        public CDA_spcMOCD_spcWSDL_spcWFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDA_spcMOCD_spcWSDL_spcWFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDA_spcMOCD_spcWSDL_spcWFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDA_spcMOCD_spcWSDL_spcWFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFResponse MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF.CDA_spcMOCD_spcWSDL_spcWF(MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFRequest request) {
            return base.Channel.CDA_spcMOCD_spcWSDL_spcWF(request);
        }
        
        public MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF_Output CDA_spcMOCD_spcWSDL_spcWF(MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF_Input CDA_spcMOCD_spcWSDL_spcWF_Input) {
            MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFRequest inValue = new MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFRequest();
            inValue.CDA_spcMOCD_spcWSDL_spcWF_Input = CDA_spcMOCD_spcWSDL_spcWF_Input;
            MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFResponse retVal = ((MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF)(this)).CDA_spcMOCD_spcWSDL_spcWF(inValue);
            return retVal.CDA_spcMOCD_spcWSDL_spcWF_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFResponse> MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF.CDA_spcMOCD_spcWSDL_spcWFAsync(MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFRequest request) {
            return base.Channel.CDA_spcMOCD_spcWSDL_spcWFAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFResponse> CDA_spcMOCD_spcWSDL_spcWFAsync(MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF_Input CDA_spcMOCD_spcWSDL_spcWF_Input) {
            MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFRequest inValue = new MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWFRequest();
            inValue.CDA_spcMOCD_spcWSDL_spcWF_Input = CDA_spcMOCD_spcWSDL_spcWF_Input;
            return ((MOCDIntegrations.CDAService.CDA_spcMOCD_spcWSDL_spcWF)(this)).CDA_spcMOCD_spcWSDL_spcWFAsync(inValue);
        }
    }
}
