//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCDIntegrations.BirthCertificate {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:HealthTypes:1")]
    public partial class FaultResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorDescEnField;
        
        private string errorDescArField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ErrorDescEn {
            get {
                return this.errorDescEnField;
            }
            set {
                this.errorDescEnField = value;
                this.RaisePropertyChanged("ErrorDescEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ErrorDescAr {
            get {
                return this.errorDescArField;
            }
            set {
                this.errorDescArField = value;
                this.RaisePropertyChanged("ErrorDescAr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:HealthTypes:1")]
    public partial class LookupType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionEnglishField;
        
        private string descriptionArabicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DescriptionEnglish {
            get {
                return this.descriptionEnglishField;
            }
            set {
                this.descriptionEnglishField = value;
                this.RaisePropertyChanged("DescriptionEnglish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string DescriptionArabic {
            get {
                return this.descriptionArabicField;
            }
            set {
                this.descriptionArabicField = value;
                this.RaisePropertyChanged("DescriptionArabic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
    public partial class BirthCertificatePullDetailsResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string birthCertificateIDField;
        
        private string fatherFullNameEnglishField;
        
        private string fatherFullNameArabicField;
        
        private LookupType fatherReligionField;
        
        private LookupType fatherNationalityField;
        
        private string motherFullNameEnglishField;
        
        private string motherFullNameArabicField;
        
        private LookupType motherReligionField;
        
        private LookupType motherNationalityField;
        
        private string babyFirstNameEnglishField;
        
        private string babyFirstNameArabicField;
        
        private LookupType babyGenderField;
        
        private string babyDateOfBirthField;
        
        private string babyDateOfBirthInHijriField;
        
        private string babyDateOfBirthInHijriWordsField;
        
        private string certificateIssueDateField;
        
        private string birthPlaceField;
        
        private string certificatePlaceOfIssueEnglishField;
        
        private string certificatePlaceOfIssueArabicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string BirthCertificateID {
            get {
                return this.birthCertificateIDField;
            }
            set {
                this.birthCertificateIDField = value;
                this.RaisePropertyChanged("BirthCertificateID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string FatherFullNameEnglish {
            get {
                return this.fatherFullNameEnglishField;
            }
            set {
                this.fatherFullNameEnglishField = value;
                this.RaisePropertyChanged("FatherFullNameEnglish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string FatherFullNameArabic {
            get {
                return this.fatherFullNameArabicField;
            }
            set {
                this.fatherFullNameArabicField = value;
                this.RaisePropertyChanged("FatherFullNameArabic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public LookupType FatherReligion {
            get {
                return this.fatherReligionField;
            }
            set {
                this.fatherReligionField = value;
                this.RaisePropertyChanged("FatherReligion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public LookupType FatherNationality {
            get {
                return this.fatherNationalityField;
            }
            set {
                this.fatherNationalityField = value;
                this.RaisePropertyChanged("FatherNationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string MotherFullNameEnglish {
            get {
                return this.motherFullNameEnglishField;
            }
            set {
                this.motherFullNameEnglishField = value;
                this.RaisePropertyChanged("MotherFullNameEnglish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string MotherFullNameArabic {
            get {
                return this.motherFullNameArabicField;
            }
            set {
                this.motherFullNameArabicField = value;
                this.RaisePropertyChanged("MotherFullNameArabic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public LookupType MotherReligion {
            get {
                return this.motherReligionField;
            }
            set {
                this.motherReligionField = value;
                this.RaisePropertyChanged("MotherReligion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public LookupType MotherNationality {
            get {
                return this.motherNationalityField;
            }
            set {
                this.motherNationalityField = value;
                this.RaisePropertyChanged("MotherNationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string BabyFirstNameEnglish {
            get {
                return this.babyFirstNameEnglishField;
            }
            set {
                this.babyFirstNameEnglishField = value;
                this.RaisePropertyChanged("BabyFirstNameEnglish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string BabyFirstNameArabic {
            get {
                return this.babyFirstNameArabicField;
            }
            set {
                this.babyFirstNameArabicField = value;
                this.RaisePropertyChanged("BabyFirstNameArabic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public LookupType BabyGender {
            get {
                return this.babyGenderField;
            }
            set {
                this.babyGenderField = value;
                this.RaisePropertyChanged("BabyGender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string BabyDateOfBirth {
            get {
                return this.babyDateOfBirthField;
            }
            set {
                this.babyDateOfBirthField = value;
                this.RaisePropertyChanged("BabyDateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string BabyDateOfBirthInHijri {
            get {
                return this.babyDateOfBirthInHijriField;
            }
            set {
                this.babyDateOfBirthInHijriField = value;
                this.RaisePropertyChanged("BabyDateOfBirthInHijri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string BabyDateOfBirthInHijriWords {
            get {
                return this.babyDateOfBirthInHijriWordsField;
            }
            set {
                this.babyDateOfBirthInHijriWordsField = value;
                this.RaisePropertyChanged("BabyDateOfBirthInHijriWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string CertificateIssueDate {
            get {
                return this.certificateIssueDateField;
            }
            set {
                this.certificateIssueDateField = value;
                this.RaisePropertyChanged("CertificateIssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string BirthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
                this.RaisePropertyChanged("BirthPlace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string CertificatePlaceOfIssueEnglish {
            get {
                return this.certificatePlaceOfIssueEnglishField;
            }
            set {
                this.certificatePlaceOfIssueEnglishField = value;
                this.RaisePropertyChanged("CertificatePlaceOfIssueEnglish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string CertificatePlaceOfIssueArabic {
            get {
                return this.certificatePlaceOfIssueArabicField;
            }
            set {
                this.certificatePlaceOfIssueArabicField = value;
                this.RaisePropertyChanged("CertificatePlaceOfIssueArabic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:HealthTypes:1")]
    public partial class ResponseStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusDescriptionEnglishField;
        
        private string statusDescriptionArabicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescriptionEnglish {
            get {
                return this.statusDescriptionEnglishField;
            }
            set {
                this.statusDescriptionEnglishField = value;
                this.RaisePropertyChanged("StatusDescriptionEnglish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusDescriptionArabic {
            get {
                return this.statusDescriptionArabicField;
            }
            set {
                this.statusDescriptionArabicField = value;
                this.RaisePropertyChanged("StatusDescriptionArabic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
    public partial class BirthCertificatePullDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseStatusType responseStatusField;
        
        private BirthCertificatePullDetailsResponseType contentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseStatusType ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("ResponseStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BirthCertificatePullDetailsResponseType Contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
                this.RaisePropertyChanged("Contents");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
    public partial class BirthCertificatePullDetailsRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emiratesIDField;
        
        private string birthCertificateIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EmiratesID {
            get {
                return this.emiratesIDField;
            }
            set {
                this.emiratesIDField = value;
                this.RaisePropertyChanged("EmiratesID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string BirthCertificateID {
            get {
                return this.birthCertificateIDField;
            }
            set {
                this.birthCertificateIDField = value;
                this.RaisePropertyChanged("BirthCertificateID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePull", ConfigurationName="BirthCertificate.BirthCertificatePullPort")]
    public interface BirthCertificatePullPort {
        
        // CODEGEN: Generating message contract since the operation getBirthCertificatePullDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePull:getBirthCertificatePull" +
            "Details", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.BirthCertificate.FaultResponseType), Action="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePull:getBirthCertificatePull" +
            "Details", Name="FaultResponse", Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsResponse getBirthCertificatePullDetails(MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePull:getBirthCertificatePull" +
            "Details", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsResponse> getBirthCertificatePullDetailsAsync(MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsRequest request);
        
        // CODEGEN: Generating message contract since the operation getBirthCertificatePullList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePull:getBirthCertificatePull" +
            "", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.BirthCertificate.FaultResponseType), Action="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePull:getBirthCertificatePull" +
            "", Name="FaultResponse", Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MOCDIntegrations.BirthCertificate.getBirthCertificatePullListResponse getBirthCertificatePullList(MOCDIntegrations.BirthCertificate.getBirthCertificatePullListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePull:getBirthCertificatePull" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<MOCDIntegrations.BirthCertificate.getBirthCertificatePullListResponse> getBirthCertificatePullListAsync(MOCDIntegrations.BirthCertificate.getBirthCertificatePullListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:HealthTypes:1")]
    public partial class RequestTrnHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdField;
        
        private string entityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string EntityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
                this.RaisePropertyChanged("EntityCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:HealthTypes:1")]
    public partial class ResponseTrnHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdField;
        
        private string entityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
                this.RaisePropertyChanged("EntityCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBirthCertificatePullDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
        public MOCDIntegrations.BirthCertificate.RequestTrnHeaderType RequestTrnHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1", Order=0)]
        public MOCDIntegrations.BirthCertificate.BirthCertificatePullDetailsRequestType BirthCertificatePullDetailsRequest;
        
        public getBirthCertificatePullDetailsRequest() {
        }
        
        public getBirthCertificatePullDetailsRequest(MOCDIntegrations.BirthCertificate.RequestTrnHeaderType RequestTrnHeader, MOCDIntegrations.BirthCertificate.BirthCertificatePullDetailsRequestType BirthCertificatePullDetailsRequest) {
            this.RequestTrnHeader = RequestTrnHeader;
            this.BirthCertificatePullDetailsRequest = BirthCertificatePullDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBirthCertificatePullDetailsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
        public MOCDIntegrations.BirthCertificate.ResponseTrnHeaderType ResponseTrnHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1", Order=0)]
        public MOCDIntegrations.BirthCertificate.BirthCertificatePullDetailsResponse BirthCertificatePullDetailsResponse;
        
        public getBirthCertificatePullDetailsResponse() {
        }
        
        public getBirthCertificatePullDetailsResponse(MOCDIntegrations.BirthCertificate.ResponseTrnHeaderType ResponseTrnHeader, MOCDIntegrations.BirthCertificate.BirthCertificatePullDetailsResponse BirthCertificatePullDetailsResponse) {
            this.ResponseTrnHeader = ResponseTrnHeader;
            this.BirthCertificatePullDetailsResponse = BirthCertificatePullDetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
    public partial class BirthCertificatePullListRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emiratesIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EmiratesID {
            get {
                return this.emiratesIDField;
            }
            set {
                this.emiratesIDField = value;
                this.RaisePropertyChanged("EmiratesID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
    public partial class BirthCertificatePullListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseStatusType responseStatusField;
        
        private BirthCertificatePullListResponseType[] contentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseStatusType ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("ResponseStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contents", Order=1)]
        public BirthCertificatePullListResponseType[] Contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
                this.RaisePropertyChanged("Contents");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
    public partial class BirthCertificatePullListResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string birthCertificateIDField;
        
        private string babyFirstNameEnglishField;
        
        private string babyFirstNameArabicField;
        
        private string babyDateOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string BirthCertificateID {
            get {
                return this.birthCertificateIDField;
            }
            set {
                this.birthCertificateIDField = value;
                this.RaisePropertyChanged("BirthCertificateID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string BabyFirstNameEnglish {
            get {
                return this.babyFirstNameEnglishField;
            }
            set {
                this.babyFirstNameEnglishField = value;
                this.RaisePropertyChanged("BabyFirstNameEnglish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string BabyFirstNameArabic {
            get {
                return this.babyFirstNameArabicField;
            }
            set {
                this.babyFirstNameArabicField = value;
                this.RaisePropertyChanged("BabyFirstNameArabic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string BabyDateOfBirth {
            get {
                return this.babyDateOfBirthField;
            }
            set {
                this.babyDateOfBirthField = value;
                this.RaisePropertyChanged("BabyDateOfBirth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBirthCertificatePullListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
        public MOCDIntegrations.BirthCertificate.RequestTrnHeaderType RequestTrnHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1", Order=0)]
        public MOCDIntegrations.BirthCertificate.BirthCertificatePullListRequestType BirthCertificatePullListRequest;
        
        public getBirthCertificatePullListRequest() {
        }
        
        public getBirthCertificatePullListRequest(MOCDIntegrations.BirthCertificate.RequestTrnHeaderType RequestTrnHeader, MOCDIntegrations.BirthCertificate.BirthCertificatePullListRequestType BirthCertificatePullListRequest) {
            this.RequestTrnHeader = RequestTrnHeader;
            this.BirthCertificatePullListRequest = BirthCertificatePullListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBirthCertificatePullListResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1")]
        public MOCDIntegrations.BirthCertificate.ResponseTrnHeaderType ResponseTrnHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ae:gov:abudhabi:DigitalDocuments:BirthCertificatePullMessages:1", Order=0)]
        public MOCDIntegrations.BirthCertificate.BirthCertificatePullListResponse BirthCertificatePullListResponse;
        
        public getBirthCertificatePullListResponse() {
        }
        
        public getBirthCertificatePullListResponse(MOCDIntegrations.BirthCertificate.ResponseTrnHeaderType ResponseTrnHeader, MOCDIntegrations.BirthCertificate.BirthCertificatePullListResponse BirthCertificatePullListResponse) {
            this.ResponseTrnHeader = ResponseTrnHeader;
            this.BirthCertificatePullListResponse = BirthCertificatePullListResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BirthCertificatePullPortChannel : MOCDIntegrations.BirthCertificate.BirthCertificatePullPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BirthCertificatePullPortClient : System.ServiceModel.ClientBase<MOCDIntegrations.BirthCertificate.BirthCertificatePullPort>, MOCDIntegrations.BirthCertificate.BirthCertificatePullPort {
        
        public BirthCertificatePullPortClient() {
        }
        
        public BirthCertificatePullPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BirthCertificatePullPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BirthCertificatePullPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BirthCertificatePullPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsResponse MOCDIntegrations.BirthCertificate.BirthCertificatePullPort.getBirthCertificatePullDetails(MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsRequest request) {
            return base.Channel.getBirthCertificatePullDetails(request);
        }
        
        public MOCDIntegrations.BirthCertificate.ResponseTrnHeaderType getBirthCertificatePullDetails(MOCDIntegrations.BirthCertificate.RequestTrnHeaderType RequestTrnHeader, MOCDIntegrations.BirthCertificate.BirthCertificatePullDetailsRequestType BirthCertificatePullDetailsRequest, out MOCDIntegrations.BirthCertificate.BirthCertificatePullDetailsResponse BirthCertificatePullDetailsResponse) {
            MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsRequest inValue = new MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsRequest();
            inValue.RequestTrnHeader = RequestTrnHeader;
            inValue.BirthCertificatePullDetailsRequest = BirthCertificatePullDetailsRequest;
            MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsResponse retVal = ((MOCDIntegrations.BirthCertificate.BirthCertificatePullPort)(this)).getBirthCertificatePullDetails(inValue);
            BirthCertificatePullDetailsResponse = retVal.BirthCertificatePullDetailsResponse;
            return retVal.ResponseTrnHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsResponse> MOCDIntegrations.BirthCertificate.BirthCertificatePullPort.getBirthCertificatePullDetailsAsync(MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsRequest request) {
            return base.Channel.getBirthCertificatePullDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsResponse> getBirthCertificatePullDetailsAsync(MOCDIntegrations.BirthCertificate.RequestTrnHeaderType RequestTrnHeader, MOCDIntegrations.BirthCertificate.BirthCertificatePullDetailsRequestType BirthCertificatePullDetailsRequest) {
            MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsRequest inValue = new MOCDIntegrations.BirthCertificate.getBirthCertificatePullDetailsRequest();
            inValue.RequestTrnHeader = RequestTrnHeader;
            inValue.BirthCertificatePullDetailsRequest = BirthCertificatePullDetailsRequest;
            return ((MOCDIntegrations.BirthCertificate.BirthCertificatePullPort)(this)).getBirthCertificatePullDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.BirthCertificate.getBirthCertificatePullListResponse MOCDIntegrations.BirthCertificate.BirthCertificatePullPort.getBirthCertificatePullList(MOCDIntegrations.BirthCertificate.getBirthCertificatePullListRequest request) {
            return base.Channel.getBirthCertificatePullList(request);
        }
        
        public MOCDIntegrations.BirthCertificate.ResponseTrnHeaderType getBirthCertificatePullList(MOCDIntegrations.BirthCertificate.RequestTrnHeaderType RequestTrnHeader, MOCDIntegrations.BirthCertificate.BirthCertificatePullListRequestType BirthCertificatePullListRequest, out MOCDIntegrations.BirthCertificate.BirthCertificatePullListResponse BirthCertificatePullListResponse) {
            MOCDIntegrations.BirthCertificate.getBirthCertificatePullListRequest inValue = new MOCDIntegrations.BirthCertificate.getBirthCertificatePullListRequest();
            inValue.RequestTrnHeader = RequestTrnHeader;
            inValue.BirthCertificatePullListRequest = BirthCertificatePullListRequest;
            MOCDIntegrations.BirthCertificate.getBirthCertificatePullListResponse retVal = ((MOCDIntegrations.BirthCertificate.BirthCertificatePullPort)(this)).getBirthCertificatePullList(inValue);
            BirthCertificatePullListResponse = retVal.BirthCertificatePullListResponse;
            return retVal.ResponseTrnHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MOCDIntegrations.BirthCertificate.getBirthCertificatePullListResponse> MOCDIntegrations.BirthCertificate.BirthCertificatePullPort.getBirthCertificatePullListAsync(MOCDIntegrations.BirthCertificate.getBirthCertificatePullListRequest request) {
            return base.Channel.getBirthCertificatePullListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.BirthCertificate.getBirthCertificatePullListResponse> getBirthCertificatePullListAsync(MOCDIntegrations.BirthCertificate.RequestTrnHeaderType RequestTrnHeader, MOCDIntegrations.BirthCertificate.BirthCertificatePullListRequestType BirthCertificatePullListRequest) {
            MOCDIntegrations.BirthCertificate.getBirthCertificatePullListRequest inValue = new MOCDIntegrations.BirthCertificate.getBirthCertificatePullListRequest();
            inValue.RequestTrnHeader = RequestTrnHeader;
            inValue.BirthCertificatePullListRequest = BirthCertificatePullListRequest;
            return ((MOCDIntegrations.BirthCertificate.BirthCertificatePullPort)(this)).getBirthCertificatePullListAsync(inValue);
        }
    }
}
