//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCDIntegrations.ZFService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class FaultHandle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private int faultIdField;
        
        private bool faultIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int faultId {
            get {
                return this.faultIdField;
            }
            set {
                this.faultIdField = value;
                this.RaisePropertyChanged("faultId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool faultIdSpecified {
            get {
                return this.faultIdFieldSpecified;
            }
            set {
                this.faultIdFieldSpecified = value;
                this.RaisePropertyChanged("faultIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class AppData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime applicationDateField;
        
        private bool applicationDateFieldSpecified;
        
        private System.Nullable<System.DateTime> approvalDateField;
        
        private bool approvalDateFieldSpecified;
        
        private string beneficiaryNameField;
        
        private string caseTypeArField;
        
        private string caseTypeEnField;
        
        private string classificationArField;
        
        private string classificationEnField;
        
        private string containerArField;
        
        private string containerEnField;
        
        private int familyNoField;
        
        private bool familyNoFieldSpecified;
        
        private string fileNoField;
        
        private string fileStatusArField;
        
        private string fileStatusEnField;
        
        private decimal helpAmountField;
        
        private bool helpAmountFieldSpecified;
        
        private string helpTypeArField;
        
        private string helpTypeEnField;
        
        private string identityNumberField;
        
        private string mobileNoField;
        
        private string nameArField;
        
        private string nameEnField;
        
        private int noOfApplicationsField;
        
        private bool noOfApplicationsFieldSpecified;
        
        private decimal noOfInstallmentField;
        
        private bool noOfInstallmentFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ApplicationDate {
            get {
                return this.applicationDateField;
            }
            set {
                this.applicationDateField = value;
                this.RaisePropertyChanged("ApplicationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationDateSpecified {
            get {
                return this.applicationDateFieldSpecified;
            }
            set {
                this.applicationDateFieldSpecified = value;
                this.RaisePropertyChanged("ApplicationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> ApprovalDate {
            get {
                return this.approvalDateField;
            }
            set {
                this.approvalDateField = value;
                this.RaisePropertyChanged("ApprovalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApprovalDateSpecified {
            get {
                return this.approvalDateFieldSpecified;
            }
            set {
                this.approvalDateFieldSpecified = value;
                this.RaisePropertyChanged("ApprovalDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string BeneficiaryName {
            get {
                return this.beneficiaryNameField;
            }
            set {
                this.beneficiaryNameField = value;
                this.RaisePropertyChanged("BeneficiaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CaseTypeAr {
            get {
                return this.caseTypeArField;
            }
            set {
                this.caseTypeArField = value;
                this.RaisePropertyChanged("CaseTypeAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CaseTypeEn {
            get {
                return this.caseTypeEnField;
            }
            set {
                this.caseTypeEnField = value;
                this.RaisePropertyChanged("CaseTypeEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ClassificationAr {
            get {
                return this.classificationArField;
            }
            set {
                this.classificationArField = value;
                this.RaisePropertyChanged("ClassificationAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ClassificationEn {
            get {
                return this.classificationEnField;
            }
            set {
                this.classificationEnField = value;
                this.RaisePropertyChanged("ClassificationEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ContainerAr {
            get {
                return this.containerArField;
            }
            set {
                this.containerArField = value;
                this.RaisePropertyChanged("ContainerAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string ContainerEn {
            get {
                return this.containerEnField;
            }
            set {
                this.containerEnField = value;
                this.RaisePropertyChanged("ContainerEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int FamilyNo {
            get {
                return this.familyNoField;
            }
            set {
                this.familyNoField = value;
                this.RaisePropertyChanged("FamilyNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FamilyNoSpecified {
            get {
                return this.familyNoFieldSpecified;
            }
            set {
                this.familyNoFieldSpecified = value;
                this.RaisePropertyChanged("FamilyNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string FileNo {
            get {
                return this.fileNoField;
            }
            set {
                this.fileNoField = value;
                this.RaisePropertyChanged("FileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string FileStatusAr {
            get {
                return this.fileStatusArField;
            }
            set {
                this.fileStatusArField = value;
                this.RaisePropertyChanged("FileStatusAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string FileStatusEn {
            get {
                return this.fileStatusEnField;
            }
            set {
                this.fileStatusEnField = value;
                this.RaisePropertyChanged("FileStatusEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal HelpAmount {
            get {
                return this.helpAmountField;
            }
            set {
                this.helpAmountField = value;
                this.RaisePropertyChanged("HelpAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HelpAmountSpecified {
            get {
                return this.helpAmountFieldSpecified;
            }
            set {
                this.helpAmountFieldSpecified = value;
                this.RaisePropertyChanged("HelpAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string HelpTypeAr {
            get {
                return this.helpTypeArField;
            }
            set {
                this.helpTypeArField = value;
                this.RaisePropertyChanged("HelpTypeAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string HelpTypeEn {
            get {
                return this.helpTypeEnField;
            }
            set {
                this.helpTypeEnField = value;
                this.RaisePropertyChanged("HelpTypeEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string IdentityNumber {
            get {
                return this.identityNumberField;
            }
            set {
                this.identityNumberField = value;
                this.RaisePropertyChanged("IdentityNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("MobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string NameAr {
            get {
                return this.nameArField;
            }
            set {
                this.nameArField = value;
                this.RaisePropertyChanged("NameAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string NameEn {
            get {
                return this.nameEnField;
            }
            set {
                this.nameEnField = value;
                this.RaisePropertyChanged("NameEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int NoOfApplications {
            get {
                return this.noOfApplicationsField;
            }
            set {
                this.noOfApplicationsField = value;
                this.RaisePropertyChanged("NoOfApplications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoOfApplicationsSpecified {
            get {
                return this.noOfApplicationsFieldSpecified;
            }
            set {
                this.noOfApplicationsFieldSpecified = value;
                this.RaisePropertyChanged("NoOfApplicationsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal NoOfInstallment {
            get {
                return this.noOfInstallmentField;
            }
            set {
                this.noOfInstallmentField = value;
                this.RaisePropertyChanged("NoOfInstallment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoOfInstallmentSpecified {
            get {
                return this.noOfInstallmentFieldSpecified;
            }
            set {
                this.noOfInstallmentFieldSpecified = value;
                this.RaisePropertyChanged("NoOfInstallmentSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class Resultmsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private bool validField;
        
        private bool validFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("Valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidSpecified {
            get {
                return this.validFieldSpecified;
            }
            set {
                this.validFieldSpecified = value;
                this.RaisePropertyChanged("ValidSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class CustomerCredential : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string securityTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SecurityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
                this.RaisePropertyChanged("SecurityToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class CustomerInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identityNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string IdentityNumber {
            get {
                return this.identityNumberField;
            }
            set {
                this.identityNumberField = value;
                this.RaisePropertyChanged("IdentityNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZFService.IZakatFundSrv")]
    public interface IZakatFundSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakatFundSrv/GetData", ReplyAction="http://tempuri.org/IZakatFundSrv/GetDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.ZFService.FaultHandle), Action="http://tempuri.org/IZakatFundSrv/GetDataFaultHandleFault", Name="FaultHandle", Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MOCDIntegrations.ZFService.StatusResult GetData(MOCDIntegrations.ZFService.CredentialInput request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakatFundSrv/GetData", ReplyAction="http://tempuri.org/IZakatFundSrv/GetDataResponse")]
        System.Threading.Tasks.Task<MOCDIntegrations.ZFService.StatusResult> GetDataAsync(MOCDIntegrations.ZFService.CredentialInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakatFundSrv/SetData", ReplyAction="http://tempuri.org/IZakatFundSrv/SetDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MOCDIntegrations.ZFService.FaultHandle), Action="http://tempuri.org/IZakatFundSrv/SetDataFaultHandleFault", Name="FaultHandle", Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MOCDIntegrations.ZFService.Resultmsg1 SetData(MOCDIntegrations.ZFService.CDataCredentialinput request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZakatFundSrv/SetData", ReplyAction="http://tempuri.org/IZakatFundSrv/SetDataResponse")]
        System.Threading.Tasks.Task<MOCDIntegrations.ZFService.Resultmsg1> SetDataAsync(MOCDIntegrations.ZFService.CDataCredentialinput request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CredentialInput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CredentialInput {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MOCDIntegrations.ZFService.CustomerInput SearchCriteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MOCDIntegrations.ZFService.CustomerCredential credential;
        
        public CredentialInput() {
        }
        
        public CredentialInput(MOCDIntegrations.ZFService.CustomerInput SearchCriteria, MOCDIntegrations.ZFService.CustomerCredential credential) {
            this.SearchCriteria = SearchCriteria;
            this.credential = credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusResult", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StatusResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MOCDIntegrations.ZFService.Resultmsg Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MOCDIntegrations.ZFService.AppData _AppData;
        
        public StatusResult() {
        }
        
        public StatusResult(MOCDIntegrations.ZFService.Resultmsg Result, MOCDIntegrations.ZFService.AppData _AppData) {
            this.Result = Result;
            this._AppData = _AppData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class CustomerDataInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identityNumberField;
        
        private InputData inputDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string IdentityNumber {
            get {
                return this.identityNumberField;
            }
            set {
                this.identityNumberField = value;
                this.RaisePropertyChanged("IdentityNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public InputData inputData {
            get {
                return this.inputDataField;
            }
            set {
                this.inputDataField = value;
                this.RaisePropertyChanged("inputData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class InputData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> caseExpiryField;
        
        private bool caseExpiryFieldSpecified;
        
        private System.Nullable<decimal> caseIdField;
        
        private bool caseIdFieldSpecified;
        
        private string caseTypeField;
        
        private string categoryField;
        
        private string centerField;
        
        private string classificationField;
        
        private System.Nullable<int> familyBookNoField;
        
        private bool familyBookNoFieldSpecified;
        
        private System.Nullable<int> familyNoField;
        
        private bool familyNoFieldSpecified;
        
        private System.Nullable<decimal> helpAmtField;
        
        private bool helpAmtFieldSpecified;
        
        private System.DateTime helpDateField;
        
        private bool helpDateFieldSpecified;
        
        private System.Nullable<int> howManyChildrenField;
        
        private bool howManyChildrenFieldSpecified;
        
        private string noteField;
        
        private string otherHelp_EnField;
        
        private string otherHelp_NameArField;
        
        private string socialAidStatusField;
        
        private System.Nullable<int> townNoField;
        
        private bool townNoFieldSpecified;
        
        private Accommodation[] zakatAccommodationsField;
        
        private IncomeSources[] zakatIncomeSourcesField;
        
        private string mobileNoFieldField;
        
        private string nameArabicFieldField;
        
        private string nameEnglishFieldField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> CaseExpiry {
            get {
                return this.caseExpiryField;
            }
            set {
                this.caseExpiryField = value;
                this.RaisePropertyChanged("CaseExpiry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CaseExpirySpecified {
            get {
                return this.caseExpiryFieldSpecified;
            }
            set {
                this.caseExpiryFieldSpecified = value;
                this.RaisePropertyChanged("CaseExpirySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> CaseId {
            get {
                return this.caseIdField;
            }
            set {
                this.caseIdField = value;
                this.RaisePropertyChanged("CaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CaseIdSpecified {
            get {
                return this.caseIdFieldSpecified;
            }
            set {
                this.caseIdFieldSpecified = value;
                this.RaisePropertyChanged("CaseIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CaseType {
            get {
                return this.caseTypeField;
            }
            set {
                this.caseTypeField = value;
                this.RaisePropertyChanged("CaseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
                this.RaisePropertyChanged("Center");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("Classification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> FamilyBookNo {
            get {
                return this.familyBookNoField;
            }
            set {
                this.familyBookNoField = value;
                this.RaisePropertyChanged("FamilyBookNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FamilyBookNoSpecified {
            get {
                return this.familyBookNoFieldSpecified;
            }
            set {
                this.familyBookNoFieldSpecified = value;
                this.RaisePropertyChanged("FamilyBookNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> FamilyNo {
            get {
                return this.familyNoField;
            }
            set {
                this.familyNoField = value;
                this.RaisePropertyChanged("FamilyNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FamilyNoSpecified {
            get {
                return this.familyNoFieldSpecified;
            }
            set {
                this.familyNoFieldSpecified = value;
                this.RaisePropertyChanged("FamilyNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> HelpAmt {
            get {
                return this.helpAmtField;
            }
            set {
                this.helpAmtField = value;
                this.RaisePropertyChanged("HelpAmt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HelpAmtSpecified {
            get {
                return this.helpAmtFieldSpecified;
            }
            set {
                this.helpAmtFieldSpecified = value;
                this.RaisePropertyChanged("HelpAmtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime HelpDate {
            get {
                return this.helpDateField;
            }
            set {
                this.helpDateField = value;
                this.RaisePropertyChanged("HelpDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HelpDateSpecified {
            get {
                return this.helpDateFieldSpecified;
            }
            set {
                this.helpDateFieldSpecified = value;
                this.RaisePropertyChanged("HelpDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> HowManyChildren {
            get {
                return this.howManyChildrenField;
            }
            set {
                this.howManyChildrenField = value;
                this.RaisePropertyChanged("HowManyChildren");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HowManyChildrenSpecified {
            get {
                return this.howManyChildrenFieldSpecified;
            }
            set {
                this.howManyChildrenFieldSpecified = value;
                this.RaisePropertyChanged("HowManyChildrenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string OtherHelp_En {
            get {
                return this.otherHelp_EnField;
            }
            set {
                this.otherHelp_EnField = value;
                this.RaisePropertyChanged("OtherHelp_En");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string OtherHelp_NameAr {
            get {
                return this.otherHelp_NameArField;
            }
            set {
                this.otherHelp_NameArField = value;
                this.RaisePropertyChanged("OtherHelp_NameAr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string SocialAidStatus {
            get {
                return this.socialAidStatusField;
            }
            set {
                this.socialAidStatusField = value;
                this.RaisePropertyChanged("SocialAidStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> TownNo {
            get {
                return this.townNoField;
            }
            set {
                this.townNoField = value;
                this.RaisePropertyChanged("TownNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TownNoSpecified {
            get {
                return this.townNoFieldSpecified;
            }
            set {
                this.townNoFieldSpecified = value;
                this.RaisePropertyChanged("TownNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=16)]
        public Accommodation[] ZakatAccommodations {
            get {
                return this.zakatAccommodationsField;
            }
            set {
                this.zakatAccommodationsField = value;
                this.RaisePropertyChanged("ZakatAccommodations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=17)]
        public IncomeSources[] ZakatIncomeSources {
            get {
                return this.zakatIncomeSourcesField;
            }
            set {
                this.zakatIncomeSourcesField = value;
                this.RaisePropertyChanged("ZakatIncomeSources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string mobileNoField {
            get {
                return this.mobileNoFieldField;
            }
            set {
                this.mobileNoFieldField = value;
                this.RaisePropertyChanged("mobileNoField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string nameArabicField {
            get {
                return this.nameArabicFieldField;
            }
            set {
                this.nameArabicFieldField = value;
                this.RaisePropertyChanged("nameArabicField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string nameEnglishField {
            get {
                return this.nameEnglishFieldField;
            }
            set {
                this.nameEnglishFieldField = value;
                this.RaisePropertyChanged("nameEnglishField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("transactionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class Accommodation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accommodationTypeField;
        
        private string conditionOfHouseField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string makaniNumberField;
        
        private string ownershipTypeField;
        
        private string personAccomodatedField;
        
        private string personInHouseField;
        
        private string roomsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AccommodationType {
            get {
                return this.accommodationTypeField;
            }
            set {
                this.accommodationTypeField = value;
                this.RaisePropertyChanged("AccommodationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ConditionOfHouse {
            get {
                return this.conditionOfHouseField;
            }
            set {
                this.conditionOfHouseField = value;
                this.RaisePropertyChanged("ConditionOfHouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string MakaniNumber {
            get {
                return this.makaniNumberField;
            }
            set {
                this.makaniNumberField = value;
                this.RaisePropertyChanged("MakaniNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string OwnershipType {
            get {
                return this.ownershipTypeField;
            }
            set {
                this.ownershipTypeField = value;
                this.RaisePropertyChanged("OwnershipType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string PersonAccomodated {
            get {
                return this.personAccomodatedField;
            }
            set {
                this.personAccomodatedField = value;
                this.RaisePropertyChanged("PersonAccomodated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string PersonInHouse {
            get {
                return this.personInHouseField;
            }
            set {
                this.personInHouseField = value;
                this.RaisePropertyChanged("PersonInHouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Rooms {
            get {
                return this.roomsField;
            }
            set {
                this.roomsField = value;
                this.RaisePropertyChanged("Rooms");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/galaxyService")]
    public partial class IncomeSources : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyNameField;
        
        private System.Nullable<decimal> incomeAmountField;
        
        private bool incomeAmountFieldSpecified;
        
        private string incomeSourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> IncomeAmount {
            get {
                return this.incomeAmountField;
            }
            set {
                this.incomeAmountField = value;
                this.RaisePropertyChanged("IncomeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncomeAmountSpecified {
            get {
                return this.incomeAmountFieldSpecified;
            }
            set {
                this.incomeAmountFieldSpecified = value;
                this.RaisePropertyChanged("IncomeAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string IncomeSource {
            get {
                return this.incomeSourceField;
            }
            set {
                this.incomeSourceField = value;
                this.RaisePropertyChanged("IncomeSource");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CDataCredentialinput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CDataCredentialinput {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MOCDIntegrations.ZFService.CustomerDataInput ProfileData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MOCDIntegrations.ZFService.CustomerCredential credential;
        
        public CDataCredentialinput() {
        }
        
        public CDataCredentialinput(MOCDIntegrations.ZFService.CustomerDataInput ProfileData, MOCDIntegrations.ZFService.CustomerCredential credential) {
            this.ProfileData = ProfileData;
            this.credential = credential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Resultmsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Resultmsg1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool Valid;
        
        public Resultmsg1() {
        }
        
        public Resultmsg1(string Message, int Status, bool Valid) {
            this.Message = Message;
            this.Status = Status;
            this.Valid = Valid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZakatFundSrvChannel : MOCDIntegrations.ZFService.IZakatFundSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZakatFundSrvClient : System.ServiceModel.ClientBase<MOCDIntegrations.ZFService.IZakatFundSrv>, MOCDIntegrations.ZFService.IZakatFundSrv {
        
        public ZakatFundSrvClient() {
        }
        
        public ZakatFundSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZakatFundSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZakatFundSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZakatFundSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.ZFService.StatusResult MOCDIntegrations.ZFService.IZakatFundSrv.GetData(MOCDIntegrations.ZFService.CredentialInput request) {
            return base.Channel.GetData(request);
        }
        
        public MOCDIntegrations.ZFService.Resultmsg GetData(MOCDIntegrations.ZFService.CustomerInput SearchCriteria, MOCDIntegrations.ZFService.CustomerCredential credential, out MOCDIntegrations.ZFService.AppData _AppData) {
            MOCDIntegrations.ZFService.CredentialInput inValue = new MOCDIntegrations.ZFService.CredentialInput();
            inValue.SearchCriteria = SearchCriteria;
            inValue.credential = credential;
            MOCDIntegrations.ZFService.StatusResult retVal = ((MOCDIntegrations.ZFService.IZakatFundSrv)(this)).GetData(inValue);
            _AppData = retVal._AppData;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.ZFService.StatusResult> GetDataAsync(MOCDIntegrations.ZFService.CredentialInput request) {
            return base.Channel.GetDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MOCDIntegrations.ZFService.Resultmsg1 MOCDIntegrations.ZFService.IZakatFundSrv.SetData(MOCDIntegrations.ZFService.CDataCredentialinput request) {
            return base.Channel.SetData(request);
        }
        
        public string SetData(MOCDIntegrations.ZFService.CustomerDataInput ProfileData, MOCDIntegrations.ZFService.CustomerCredential credential, out int Status, out bool Valid) {
            MOCDIntegrations.ZFService.CDataCredentialinput inValue = new MOCDIntegrations.ZFService.CDataCredentialinput();
            inValue.ProfileData = ProfileData;
            inValue.credential = credential;
            MOCDIntegrations.ZFService.Resultmsg1 retVal = ((MOCDIntegrations.ZFService.IZakatFundSrv)(this)).SetData(inValue);
            Status = retVal.Status;
            Valid = retVal.Valid;
            return retVal.Message;
        }
        
        public System.Threading.Tasks.Task<MOCDIntegrations.ZFService.Resultmsg1> SetDataAsync(MOCDIntegrations.ZFService.CDataCredentialinput request) {
            return base.Channel.SetDataAsync(request);
        }
    }
}
