//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCDIntegrations.ICP_PersonalProfile
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://id.gov.ae/ws/PersonInquiryService", ConfigurationName = "ICP_PersonalProfile.PersonInquiryService")]
    public interface PersonInquiryService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://id.gov.ae/ws/PersonInquiryService/personInquiry", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonResponseType))]
        System.Threading.Tasks.Task<ICP_PersonalProfile.personInquiryResponse> personInquiryAsync(ICP_PersonalProfile.personInquiryRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PersonInquiryRequestType
    {

        private HeaderType headerField;

        private PersonInquiryRequestBodyType bodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://id.gov.ae/schema/commontypes", Order = 0)]
        public HeaderType Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PersonInquiryRequestBodyType Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/commontypes")]
    public partial class HeaderType
    {

        private string serviceNameField;

        private string sourceChannelField;

        private string serviceVersionField;

        private string serviceLanguageField;

        private string userNameField;

        private string passwordField;

        private byte[] hashField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string sourceChannel
        {
            get
            {
                return this.sourceChannelField;
            }
            set
            {
                this.sourceChannelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string serviceVersion
        {
            get
            {
                return this.serviceVersionField;
            }
            set
            {
                this.serviceVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string serviceLanguage
        {
            get
            {
                return this.serviceLanguageField;
            }
            set
            {
                this.serviceLanguageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 6)]
        public byte[] hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class ChildType
    {

        private string iDNField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IDN
        {
            get
            {
                return this.iDNField;
            }
            set
            {
                this.iDNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class RelativeType
    {

        private DetailType relationField;

        private PersonNameType nameField;

        private DetailType nationalityField;

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        private string unField;

        private IdentityCardType identityCardField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DetailType relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PersonNameType name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public DetailType nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string UN
        {
            get
            {
                return this.unField;
            }
            set
            {
                this.unField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public IdentityCardType identityCard
        {
            get
            {
                return this.identityCardField;
            }
            set
            {
                this.identityCardField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class DetailType
    {

        private long idField;

        private bool idFieldSpecified;

        private string descriptionArabicField;

        private string descriptionEnglishField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string descriptionArabic
        {
            get
            {
                return this.descriptionArabicField;
            }
            set
            {
                this.descriptionArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string descriptionEnglish
        {
            get
            {
                return this.descriptionEnglishField;
            }
            set
            {
                this.descriptionEnglishField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PersonNameType
    {

        private string firstNameArabicField;

        private string firstNameEnglishField;

        private string secondNameArabicField;

        private string secondNameEnglishField;

        private string thirdNameArabicField;

        private string thirdNameEnglishField;

        private string fourthNameArabicField;

        private string fourthNameEnglishField;

        private string fullNameArabicField;

        private string fullNameEnglishField;

        private string familyNameArabicField;

        private string familyNameEnglishField;

        private string clanNameArabicField;

        private string clanNameEnglishField;

        private DetailType tribeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string firstNameArabic
        {
            get
            {
                return this.firstNameArabicField;
            }
            set
            {
                this.firstNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string firstNameEnglish
        {
            get
            {
                return this.firstNameEnglishField;
            }
            set
            {
                this.firstNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string secondNameArabic
        {
            get
            {
                return this.secondNameArabicField;
            }
            set
            {
                this.secondNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string secondNameEnglish
        {
            get
            {
                return this.secondNameEnglishField;
            }
            set
            {
                this.secondNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string thirdNameArabic
        {
            get
            {
                return this.thirdNameArabicField;
            }
            set
            {
                this.thirdNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string thirdNameEnglish
        {
            get
            {
                return this.thirdNameEnglishField;
            }
            set
            {
                this.thirdNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string fourthNameArabic
        {
            get
            {
                return this.fourthNameArabicField;
            }
            set
            {
                this.fourthNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string fourthNameEnglish
        {
            get
            {
                return this.fourthNameEnglishField;
            }
            set
            {
                this.fourthNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string fullNameArabic
        {
            get
            {
                return this.fullNameArabicField;
            }
            set
            {
                this.fullNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string fullNameEnglish
        {
            get
            {
                return this.fullNameEnglishField;
            }
            set
            {
                this.fullNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string familyNameArabic
        {
            get
            {
                return this.familyNameArabicField;
            }
            set
            {
                this.familyNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string familyNameEnglish
        {
            get
            {
                return this.familyNameEnglishField;
            }
            set
            {
                this.familyNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string clanNameArabic
        {
            get
            {
                return this.clanNameArabicField;
            }
            set
            {
                this.clanNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string clanNameEnglish
        {
            get
            {
                return this.clanNameEnglishField;
            }
            set
            {
                this.clanNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public DetailType tribe
        {
            get
            {
                return this.tribeField;
            }
            set
            {
                this.tribeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class IdentityCardType
    {

        private string iDNField;

        private string iDNBackNumberField;

        private System.DateTime issueDateField;

        private bool issueDateFieldSpecified;

        private System.DateTime expiryDateField;

        private bool expiryDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IDN
        {
            get
            {
                return this.iDNField;
            }
            set
            {
                this.iDNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string IDNBackNumber
        {
            get
            {
                return this.iDNBackNumberField;
            }
            set
            {
                this.iDNBackNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime issueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool issueDateSpecified
        {
            get
            {
                return this.issueDateFieldSpecified;
            }
            set
            {
                this.issueDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime expiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PersonProfileWifeType
    {

        private PersonNameType nameField;

        private DetailType nationalityField;

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        private string unField;

        private IdentityCardType identityCardField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PersonNameType name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public DetailType nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string UN
        {
            get
            {
                return this.unField;
            }
            set
            {
                this.unField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public IdentityCardType identityCard
        {
            get
            {
                return this.identityCardField;
            }
            set
            {
                this.identityCardField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class QualificationType
    {

        private DetailType countryField;

        private string academyNameField;

        private DetailType specializationField;

        private string gradeField;

        private System.DateTime qualificationDateField;

        private bool qualificationDateFieldSpecified;

        private string noteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DetailType country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string academyName
        {
            get
            {
                return this.academyNameField;
            }
            set
            {
                this.academyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public DetailType specialization
        {
            get
            {
                return this.specializationField;
            }
            set
            {
                this.specializationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.DateTime qualificationDate
        {
            get
            {
                return this.qualificationDateField;
            }
            set
            {
                this.qualificationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qualificationDateSpecified
        {
            get
            {
                return this.qualificationDateFieldSpecified;
            }
            set
            {
                this.qualificationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class ImmigrationFileType
    {

        private DetailType statusField;

        private string fileNoField;

        private DetailType departmentField;

        private string yearField;

        private DetailType fileTypeField;

        private string fileSequenceField;

        private System.DateTime issueDateField;

        private bool issueDateFieldSpecified;

        private System.DateTime expiryDateField;

        private bool expiryDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DetailType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string fileNo
        {
            get
            {
                return this.fileNoField;
            }
            set
            {
                this.fileNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public DetailType department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear", Order = 3)]
        public string year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public DetailType fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string fileSequence
        {
            get
            {
                return this.fileSequenceField;
            }
            set
            {
                this.fileSequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public System.DateTime issueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool issueDateSpecified
        {
            get
            {
                return this.issueDateFieldSpecified;
            }
            set
            {
                this.issueDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public System.DateTime expiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class AbroadAddressType
    {

        private DetailType countryField;

        private string phoneNoField;

        private string detailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DetailType country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string phoneNo
        {
            get
            {
                return this.phoneNoField;
            }
            set
            {
                this.phoneNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class LocalAddressType
    {

        private DetailType emirateField;

        private DetailType cityField;

        private DetailType areaField;

        private DetailType streetField;

        private string buildingNumberField;

        private string buildingField;

        private string poboxNoField;

        private string mobileNoField;

        private string secondMobileNoField;

        private string homePhoneField;

        private string workPhoneField;

        private string faxField;

        private string emailAddressField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DetailType emirate
        {
            get
            {
                return this.emirateField;
            }
            set
            {
                this.emirateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public DetailType city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public DetailType area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public DetailType street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string buildingNumber
        {
            get
            {
                return this.buildingNumberField;
            }
            set
            {
                this.buildingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string building
        {
            get
            {
                return this.buildingField;
            }
            set
            {
                this.buildingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string poboxNo
        {
            get
            {
                return this.poboxNoField;
            }
            set
            {
                this.poboxNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string mobileNo
        {
            get
            {
                return this.mobileNoField;
            }
            set
            {
                this.mobileNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string secondMobileNo
        {
            get
            {
                return this.secondMobileNoField;
            }
            set
            {
                this.secondMobileNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string homePhone
        {
            get
            {
                return this.homePhoneField;
            }
            set
            {
                this.homePhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string workPhone
        {
            get
            {
                return this.workPhoneField;
            }
            set
            {
                this.workPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string emailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class AddressType
    {

        private LocalAddressType localAddressField;

        private AbroadAddressType abroadAddressField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public LocalAddressType localAddress
        {
            get
            {
                return this.localAddressField;
            }
            set
            {
                this.localAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public AbroadAddressType abroadAddress
        {
            get
            {
                return this.abroadAddressField;
            }
            set
            {
                this.abroadAddressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class SponsorType
    {

        private string nameArabicField;

        private string nameEnglishField;

        private DetailType departmentField;

        private string sponsorIDNField;

        private long sponsorNoField;

        private bool sponsorNoFieldSpecified;

        private AddressType[] addressesField;

        private DetailType sponsorTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string nameArabic
        {
            get
            {
                return this.nameArabicField;
            }
            set
            {
                this.nameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string nameEnglish
        {
            get
            {
                return this.nameEnglishField;
            }
            set
            {
                this.nameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public DetailType department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string sponsorIDN
        {
            get
            {
                return this.sponsorIDNField;
            }
            set
            {
                this.sponsorIDNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public long sponsorNo
        {
            get
            {
                return this.sponsorNoField;
            }
            set
            {
                this.sponsorNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sponsorNoSpecified
        {
            get
            {
                return this.sponsorNoFieldSpecified;
            }
            set
            {
                this.sponsorNoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("address", IsNullable = false)]
        public AddressType[] addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public DetailType sponsorType
        {
            get
            {
                return this.sponsorTypeField;
            }
            set
            {
                this.sponsorTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PassportType
    {

        private string passportNoField;

        private DetailType passportTypeField;

        private System.DateTime issueDateField;

        private bool issueDateFieldSpecified;

        private System.DateTime expiryDateField;

        private bool expiryDateFieldSpecified;

        private DetailType issueCountryField;

        private string issuePlaceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string passportNo
        {
            get
            {
                return this.passportNoField;
            }
            set
            {
                this.passportNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public DetailType passportType
        {
            get
            {
                return this.passportTypeField;
            }
            set
            {
                this.passportTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime issueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool issueDateSpecified
        {
            get
            {
                return this.issueDateFieldSpecified;
            }
            set
            {
                this.issueDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime expiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public DetailType issueCountry
        {
            get
            {
                return this.issueCountryField;
            }
            set
            {
                this.issueCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string issuePlace
        {
            get
            {
                return this.issuePlaceField;
            }
            set
            {
                this.issuePlaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PersonProfileType
    {

        private string unField;

        private IdentityCardType identityCardField;

        private string cardSerialNoField;

        private DetailType nationalityField;

        private DetailType titleField;

        private PersonNameType personNameField;

        private string khulasitQaidNoField;

        private string familyBookNoField;

        private System.DateTime familyBookStartDateField;

        private bool familyBookStartDateFieldSpecified;

        private System.DateTime familyBookCreateDateField;

        private bool familyBookCreateDateFieldSpecified;

        private System.DateTime citizenshipStartDateField;

        private bool citizenshipStartDateFieldSpecified;

        private string familyBookRelationField;

        private string edbarahNoField;

        private DetailType genderField;

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        private DetailType birthCountryField;

        private DetailType birthEmirateField;

        private DetailType birthCityField;

        private string birthPlaceArabicField;

        private string birthPlaceEnglishField;

        private string birthCertificateNoField;

        private DetailType maritalStatusField;

        private DetailType religionField;

        private string pimarylangCodeField;

        private PassportType passportField;

        private SponsorType sponsorField;

        private DetailType faithField;

        private DetailType personTypeField;

        private string personClassificationField;

        private ImmigrationFileType immigrationFileField;

        private DetailType occupationField;

        private string companyTypeCodeField;

        private string companyCodeField;

        private string companyArField;

        private string companyEnField;

        private string motherNameArabicField;

        private string motherNameEnglishField;

        private string motherFirstNameArabicField;

        private string motherFirstNameEnglishField;

        private DetailType previousNationalityField;

        private AddressType[] addressesField;

        private QualificationType qualificationField;

        private string wives_countField;

        private PersonProfileWifeType[] wivesField;

        private RelativeType[] relativesField;

        private bool isBlackListedField;

        private bool isBlackListedFieldSpecified;

        private bool isInsideCountryField;

        private bool isInsideCountryFieldSpecified;

        private string familyCountField;

        private string familyMaleCountField;

        private string familyFemaleCountField;

        private string motherChildCountField;

        private ChildType[] motherChildrenField;

        private long disabilityField;

        private bool disabilityFieldSpecified;

        private string freeEducationField;

        private string freeHealthField;

        private string bloodTypeField;

        private string socialSupportStatusField;

        private string hasSpecialNationalityField;

        private System.DateTime lastExitDateField;

        private bool lastExitDateFieldSpecified;

        private System.DateTime lastEntryDateField;

        private bool lastEntryDateFieldSpecified;

        private string icaDeniedField;

        private string fatherHasOnlySonField;

        private string motherHasOnlySonField;

        private byte[] signatureField;

        private byte[] portraitField;

        private byte[] pr_portraitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string UN
        {
            get
            {
                return this.unField;
            }
            set
            {
                this.unField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public IdentityCardType identityCard
        {
            get
            {
                return this.identityCardField;
            }
            set
            {
                this.identityCardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string cardSerialNo
        {
            get
            {
                return this.cardSerialNoField;
            }
            set
            {
                this.cardSerialNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public DetailType nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public DetailType title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public PersonNameType personName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string khulasitQaidNo
        {
            get
            {
                return this.khulasitQaidNoField;
            }
            set
            {
                this.khulasitQaidNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string familyBookNo
        {
            get
            {
                return this.familyBookNoField;
            }
            set
            {
                this.familyBookNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public System.DateTime familyBookStartDate
        {
            get
            {
                return this.familyBookStartDateField;
            }
            set
            {
                this.familyBookStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool familyBookStartDateSpecified
        {
            get
            {
                return this.familyBookStartDateFieldSpecified;
            }
            set
            {
                this.familyBookStartDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public System.DateTime familyBookCreateDate
        {
            get
            {
                return this.familyBookCreateDateField;
            }
            set
            {
                this.familyBookCreateDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool familyBookCreateDateSpecified
        {
            get
            {
                return this.familyBookCreateDateFieldSpecified;
            }
            set
            {
                this.familyBookCreateDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public System.DateTime citizenshipStartDate
        {
            get
            {
                return this.citizenshipStartDateField;
            }
            set
            {
                this.citizenshipStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool citizenshipStartDateSpecified
        {
            get
            {
                return this.citizenshipStartDateFieldSpecified;
            }
            set
            {
                this.citizenshipStartDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 11)]
        public string familyBookRelation
        {
            get
            {
                return this.familyBookRelationField;
            }
            set
            {
                this.familyBookRelationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string edbarahNo
        {
            get
            {
                return this.edbarahNoField;
            }
            set
            {
                this.edbarahNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public DetailType gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public System.DateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public DetailType birthCountry
        {
            get
            {
                return this.birthCountryField;
            }
            set
            {
                this.birthCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public DetailType birthEmirate
        {
            get
            {
                return this.birthEmirateField;
            }
            set
            {
                this.birthEmirateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public DetailType birthCity
        {
            get
            {
                return this.birthCityField;
            }
            set
            {
                this.birthCityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string birthPlaceArabic
        {
            get
            {
                return this.birthPlaceArabicField;
            }
            set
            {
                this.birthPlaceArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string birthPlaceEnglish
        {
            get
            {
                return this.birthPlaceEnglishField;
            }
            set
            {
                this.birthPlaceEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string birthCertificateNo
        {
            get
            {
                return this.birthCertificateNoField;
            }
            set
            {
                this.birthCertificateNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public DetailType maritalStatus
        {
            get
            {
                return this.maritalStatusField;
            }
            set
            {
                this.maritalStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public DetailType religion
        {
            get
            {
                return this.religionField;
            }
            set
            {
                this.religionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 23)]
        public string pimarylangCode
        {
            get
            {
                return this.pimarylangCodeField;
            }
            set
            {
                this.pimarylangCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public PassportType passport
        {
            get
            {
                return this.passportField;
            }
            set
            {
                this.passportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public SponsorType sponsor
        {
            get
            {
                return this.sponsorField;
            }
            set
            {
                this.sponsorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public DetailType faith
        {
            get
            {
                return this.faithField;
            }
            set
            {
                this.faithField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 27)]
        public DetailType personType
        {
            get
            {
                return this.personTypeField;
            }
            set
            {
                this.personTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 28)]
        public string personClassification
        {
            get
            {
                return this.personClassificationField;
            }
            set
            {
                this.personClassificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 29)]
        public ImmigrationFileType immigrationFile
        {
            get
            {
                return this.immigrationFileField;
            }
            set
            {
                this.immigrationFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 30)]
        public DetailType occupation
        {
            get
            {
                return this.occupationField;
            }
            set
            {
                this.occupationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 31)]
        public string companyTypeCode
        {
            get
            {
                return this.companyTypeCodeField;
            }
            set
            {
                this.companyTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 32)]
        public string companyCode
        {
            get
            {
                return this.companyCodeField;
            }
            set
            {
                this.companyCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 33)]
        public string companyAr
        {
            get
            {
                return this.companyArField;
            }
            set
            {
                this.companyArField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 34)]
        public string companyEn
        {
            get
            {
                return this.companyEnField;
            }
            set
            {
                this.companyEnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 35)]
        public string motherNameArabic
        {
            get
            {
                return this.motherNameArabicField;
            }
            set
            {
                this.motherNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 36)]
        public string motherNameEnglish
        {
            get
            {
                return this.motherNameEnglishField;
            }
            set
            {
                this.motherNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 37)]
        public string motherFirstNameArabic
        {
            get
            {
                return this.motherFirstNameArabicField;
            }
            set
            {
                this.motherFirstNameArabicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 38)]
        public string motherFirstNameEnglish
        {
            get
            {
                return this.motherFirstNameEnglishField;
            }
            set
            {
                this.motherFirstNameEnglishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 39)]
        public DetailType previousNationality
        {
            get
            {
                return this.previousNationalityField;
            }
            set
            {
                this.previousNationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 40)]
        [System.Xml.Serialization.XmlArrayItemAttribute("address", IsNullable = false)]
        public AddressType[] addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 41)]
        public QualificationType qualification
        {
            get
            {
                return this.qualificationField;
            }
            set
            {
                this.qualificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 42)]
        public string wives_count
        {
            get
            {
                return this.wives_countField;
            }
            set
            {
                this.wives_countField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 43)]
        [System.Xml.Serialization.XmlArrayItemAttribute("wife", IsNullable = false)]
        public PersonProfileWifeType[] wives
        {
            get
            {
                return this.wivesField;
            }
            set
            {
                this.wivesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 44)]
        [System.Xml.Serialization.XmlArrayItemAttribute("relative", IsNullable = false)]
        public RelativeType[] relatives
        {
            get
            {
                return this.relativesField;
            }
            set
            {
                this.relativesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 45)]
        public bool isBlackListed
        {
            get
            {
                return this.isBlackListedField;
            }
            set
            {
                this.isBlackListedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isBlackListedSpecified
        {
            get
            {
                return this.isBlackListedFieldSpecified;
            }
            set
            {
                this.isBlackListedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 46)]
        public bool isInsideCountry
        {
            get
            {
                return this.isInsideCountryField;
            }
            set
            {
                this.isInsideCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isInsideCountrySpecified
        {
            get
            {
                return this.isInsideCountryFieldSpecified;
            }
            set
            {
                this.isInsideCountryFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 47)]
        public string familyCount
        {
            get
            {
                return this.familyCountField;
            }
            set
            {
                this.familyCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 48)]
        public string familyMaleCount
        {
            get
            {
                return this.familyMaleCountField;
            }
            set
            {
                this.familyMaleCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 49)]
        public string familyFemaleCount
        {
            get
            {
                return this.familyFemaleCountField;
            }
            set
            {
                this.familyFemaleCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 50)]
        public string motherChildCount
        {
            get
            {
                return this.motherChildCountField;
            }
            set
            {
                this.motherChildCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 51)]
        [System.Xml.Serialization.XmlArrayItemAttribute("child", IsNullable = false)]
        public ChildType[] motherChildren
        {
            get
            {
                return this.motherChildrenField;
            }
            set
            {
                this.motherChildrenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 52)]
        public long disability
        {
            get
            {
                return this.disabilityField;
            }
            set
            {
                this.disabilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disabilitySpecified
        {
            get
            {
                return this.disabilityFieldSpecified;
            }
            set
            {
                this.disabilityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 53)]
        public string freeEducation
        {
            get
            {
                return this.freeEducationField;
            }
            set
            {
                this.freeEducationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 54)]
        public string freeHealth
        {
            get
            {
                return this.freeHealthField;
            }
            set
            {
                this.freeHealthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 55)]
        public string bloodType
        {
            get
            {
                return this.bloodTypeField;
            }
            set
            {
                this.bloodTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 56)]
        public string socialSupportStatus
        {
            get
            {
                return this.socialSupportStatusField;
            }
            set
            {
                this.socialSupportStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 57)]
        public string hasSpecialNationality
        {
            get
            {
                return this.hasSpecialNationalityField;
            }
            set
            {
                this.hasSpecialNationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 58)]
        public System.DateTime lastExitDate
        {
            get
            {
                return this.lastExitDateField;
            }
            set
            {
                this.lastExitDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastExitDateSpecified
        {
            get
            {
                return this.lastExitDateFieldSpecified;
            }
            set
            {
                this.lastExitDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 59)]
        public System.DateTime lastEntryDate
        {
            get
            {
                return this.lastEntryDateField;
            }
            set
            {
                this.lastEntryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastEntryDateSpecified
        {
            get
            {
                return this.lastEntryDateFieldSpecified;
            }
            set
            {
                this.lastEntryDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 60)]
        public string icaDenied
        {
            get
            {
                return this.icaDeniedField;
            }
            set
            {
                this.icaDeniedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 61)]
        public string fatherHasOnlySon
        {
            get
            {
                return this.fatherHasOnlySonField;
            }
            set
            {
                this.fatherHasOnlySonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 62)]
        public string motherHasOnlySon
        {
            get
            {
                return this.motherHasOnlySonField;
            }
            set
            {
                this.motherHasOnlySonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 63)]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 64)]
        public byte[] portrait
        {
            get
            {
                return this.portraitField;
            }
            set
            {
                this.portraitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 65)]
        public byte[] pr_portrait
        {
            get
            {
                return this.pr_portraitField;
            }
            set
            {
                this.pr_portraitField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonInquiryResponseBodyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class CommonResponseType
    {

        private string transactionRefNoField;

        private string responseCodeField;

        private string responseDescriptionField;

        private string responseDescriptionArabicField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string transactionRefNo
        {
            get
            {
                return this.transactionRefNoField;
            }
            set
            {
                this.transactionRefNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string responseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string responseDescriptionArabic
        {
            get
            {
                return this.responseDescriptionArabicField;
            }
            set
            {
                this.responseDescriptionArabicField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PersonInquiryResponseBodyType : CommonResponseType
    {

        private PersonProfileType personProfileField;

        private System.DateTime timestampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PersonProfileType personProfile
        {
            get
            {
                return this.personProfileField;
            }
            set
            {
                this.personProfileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PersonInquiryResponseType
    {

        private HeaderType headerField;

        private PersonInquiryResponseBodyType bodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://id.gov.ae/schema/commontypes", Order = 0)]
        public HeaderType Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PersonInquiryResponseBodyType Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class FileType
    {

        private string fileTypeField;

        private string fileNoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string fileNo
        {
            get
            {
                return this.fileNoField;
            }
            set
            {
                this.fileNoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class DocumentType
    {

        private string documentTypeField;

        private string documentNoField;

        private string documentNationalityField;

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string documentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string documentNo
        {
            get
            {
                return this.documentNoField;
            }
            set
            {
                this.documentNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 2)]
        public string documentNationality
        {
            get
            {
                return this.documentNationalityField;
            }
            set
            {
                this.documentNationalityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PersonInquiryType
    {

        private object itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IDN", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("UN", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("document", typeof(DocumentType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("file", typeof(FileType), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        IDN,

        /// <remarks/>
        UN,

        /// <remarks/>
        document,

        /// <remarks/>
        file,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://id.gov.ae/schema/personInquiry")]
    public partial class PersonInquiryRequestBodyType
    {

        private string transactionRefNoField;

        private PersonInquiryType inquiryField;

        private string oTPField;

        private string txnTypeField;

        private System.DateTime timestampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string transactionRefNo
        {
            get
            {
                return this.transactionRefNoField;
            }
            set
            {
                this.transactionRefNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PersonInquiryType inquiry
        {
            get
            {
                return this.inquiryField;
            }
            set
            {
                this.inquiryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string OTP
        {
            get
            {
                return this.oTPField;
            }
            set
            {
                this.oTPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 3)]
        public string txnType
        {
            get
            {
                return this.txnTypeField;
            }
            set
            {
                this.txnTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class personInquiryRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://id.gov.ae/ws/personInquiry", Order = 0)]
        public ICP_PersonalProfile.PersonInquiryRequestType personInquiry;

        public personInquiryRequest()
        {
        }

        public personInquiryRequest(ICP_PersonalProfile.PersonInquiryRequestType personInquiry)
        {
            this.personInquiry = personInquiry;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class personInquiryResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "personInquiryResponse", Namespace = "http://id.gov.ae/ws/personInquiry", Order = 0)]
        public ICP_PersonalProfile.PersonInquiryResponseType personInquiryResponse1;

        public personInquiryResponse()
        {
        }

        public personInquiryResponse(ICP_PersonalProfile.PersonInquiryResponseType personInquiryResponse1)
        {
            this.personInquiryResponse1 = personInquiryResponse1;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PersonInquiryServiceChannel : ICP_PersonalProfile.PersonInquiryService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PersonInquiryServiceClient : System.ServiceModel.ClientBase<ICP_PersonalProfile.PersonInquiryService>, ICP_PersonalProfile.PersonInquiryService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public PersonInquiryServiceClient() :
                base(PersonInquiryServiceClient.GetDefaultBinding(), PersonInquiryServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.getPersonInquiry_ICAsoaphttps.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PersonInquiryServiceClient(EndpointConfiguration endpointConfiguration) :
                base(PersonInquiryServiceClient.GetBindingForEndpoint(endpointConfiguration), PersonInquiryServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PersonInquiryServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(PersonInquiryServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PersonInquiryServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(PersonInquiryServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PersonInquiryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICP_PersonalProfile.personInquiryResponse> ICP_PersonalProfile.PersonInquiryService.personInquiryAsync(ICP_PersonalProfile.personInquiryRequest request)
        {
            return base.Channel.personInquiryAsync(request);
        }

        public System.Threading.Tasks.Task<ICP_PersonalProfile.personInquiryResponse> personInquiryAsync(ICP_PersonalProfile.PersonInquiryRequestType personInquiry)
        {
            ICP_PersonalProfile.personInquiryRequest inValue = new ICP_PersonalProfile.personInquiryRequest();
            inValue.personInquiry = personInquiry;
            return ((ICP_PersonalProfile.PersonInquiryService)(this)).personInquiryAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.getPersonInquiry_ICAsoaphttps))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.getPersonInquiry_ICAsoaphttps))
            {
                return new System.ServiceModel.EndpointAddress("https://integrate.gsb.government.ae/ws/getPersonInquiry_ICA.getPersonInquiry_ICAs" +
                        "oaphttps/1.0");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PersonInquiryServiceClient.GetBindingForEndpoint(EndpointConfiguration.getPersonInquiry_ICAsoaphttps);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PersonInquiryServiceClient.GetEndpointAddress(EndpointConfiguration.getPersonInquiry_ICAsoaphttps);
        }

        public enum EndpointConfiguration
        {

            getPersonInquiry_ICAsoaphttps,
        }
    }
}

